### ISSUE TITLE
Resolution for "deactivated" document should return HTTP 200 OK  instead of HTTP 410 Gone

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#1007]
Now that we are returning proper resolution result with empty document and ‘deactivated’ flag in DID Document Metadata we should return HTTP 200 OK instead of  error code HTTP 410 Gone.

**Comment by sandrask** [comment]
@csuwildcat and @troyronda confirmed that this is desired behaviour during weekly.

**Comment by troyronda** [comment]
We also need resolution to https://github.com/w3c/did-core/pull/543 to complete.

**Comment by troyronda** [comment]
Linked: #1015

**Comment by troyronda** [comment]
In https://github.com/decentralized-identity/sidetree/pull/1029
