### ISSUE TITLE
Type language is too strong

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#1032]
docs/spec/operations.md

> The object ****MAY**** contain a `type` property, and if present, its value ****MUST**** be a type string, of a length and composition defined by the implementation, that signifies the type of entity a DID represents. The value ****MUST NOT**** be anything that represents humans, groups of humans, or any human-identifying classification - an implementation ****SHALL NOT**** override this directive, and any attempt to do so shall render the implementation non-conformant to this specification.

A couple thoughts:

- It seems odd to single-out `type` with such strong language.
- DID Methods are not required to support `type`.

**Comment by OR13** [comment]
I would just delete this part:

> The value MUST NOT be anything that represents humans, groups of humans, or any human-identifying classification - an implementation SHALL NOT override this directive, and any attempt to do so shall render the implementation non-conformant to this specification.

who decides what "human-identifying classification" is, do "🌈🐻" or "🧻👐" count?

and more importantly... this is fundamentally not enforceable... see the examples above... I would never have thought that emojis identified groups of people but its 2021... I am sure by 2030 there will be other ways...
