### ISSUE TITLE
Allow for a partitioned anchoring system

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#1034]
In some anchoring systems, anchors can be partitioned among multiple systems rather than being held in a single common system. In other words, the overall system becomes a network of anchoring systems.

In these situations, observers need to know which system(s) know the most recent anchor for a DID. This property should be set by the DID controller/owner during `Create` and `Recover`. When an observer has previously processed a Sidetree suffix from the network of anchoring systems, that observer can also determine if they hold the most recent anchor based on that property.

To enable a Sidetree-based DID method that has a partitioned anchoring system, we should add an optional property to `Create` and `Recover` that enables an observer to find the head anchor for a DID. E.g., the property could be called `anchorSources`, `anchorHeadSources` or similar. DID methods that have a single common system can omit this property as the source is implicitly already defined.

**Comment by csuwildcat** [comment]
Could we go with `anchorOrigin` or `anchorOrigins`? feel like that might be a bit more self-explanatory.

**Comment by troyronda** [comment]
@csuwildcat updated PR with anchorOrigins
