### ISSUE TITLE
Odd rendering of Releases text in spec

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#1042]
"Github releasesRelease:"

<img width="822" alt="Screen Shot 2021-02-16 at 11 08 01 AM" src="https://user-images.githubusercontent.com/1906596/108089165-4a82b100-7047-11eb-83dc-2235df220004.png">

**Comment by csuwildcat** [comment]
This is just the auto-linking CSS pretty print styles lacking a small attr selector in a CSS rule. I just updated Spec-Up's CSS to correct it, and the render should be right when we update the dep to latest for the next PR

**Comment by troyronda** [comment]
Fixed
