### ISSUE TITLE
Unresolvable test DIDs

### ISSUE THREAD

**Issue by peacekeeper** [decentralized-identity/sidetree#1071]
Quick questions about the current state of did:ion....

1. We created a test DID `did:ion:test:EiBISbrXlYeXjxQ7uf2tQoE0dUxpmkpJMovhxCGKKGycEg`, which is resolvable via our local ION node, but not resolvable via `curl -X GET https://beta.discover.did.microsoft.com/1.0/identifiers/did:ion:test:EiBISbrXlYeXjxQ7uf2tQoE0dUxpmkpJMovhxCGKKGycEg`.
2. Is the Universal Resolver driver for `did:ion` up to date? It says last updated 4 months ago. See https://hub.docker.com/r/identityfoundation/driver-did-ion.
3. Any recommendation for a "good did:ion example DID" that we can display in the frontend at https://dev.uniresolver.io/?

**Comment by thehenrytsai** [comment]
Please refer to https://github.com/decentralized-identity/ion/issues/177, closing this issue since this is more of an ION issue.
