### ISSUE TITLE
Node vs C#

### ISSUE THREAD

**Issue by acrigney** [decentralized-identity/sidetree#1079]
Hi Guys,
                  Just wondering if you will be doing C# reference apps and also why did you choose Node over C#?
Best Regards,
                      Alistair

**Comment by thehenrytsai** [comment]
Super late, but no plan on C# reference anytime soon but community contribution is always welcome! We chose Node because it has arguably the largest community, developer, platform, and library support.

**Comment by decentralgabe** [comment]
Closing, will address in sidetree-impl.
