### ISSUE TITLE
Run local node with IPFS  write error

### ISSUE THREAD

**Issue by KunPengRen** [decentralized-identity/sidetree#1165]
I am run a local ION node with regest bitcoin network.
I faced some problem when ION write the data to ipfs network, with the below error output
```
IPFS write error response status: 500
IPFS write error body: {"Message":"expected a file argument","Code":0,"Type":"error"}
```
I can upload the file by ipfs webui directly. I am running ipfs node in laptop, do I need a virtual server to run ipfs with a real IP?

**Comment by BenjaminMoe** [comment]
Ion should be able to write to ipfs if ipfs is running on the same server, and the url has been configured correctly. If you want to checkout getting Ion with Regtest to work on a Raspberry Pi you can try the documentation here: https://github.com/transmute-industries/sidetree.js/blob/main/packages/did-method-ion/docs/install-ion-dev.md

**Comment by rodolfomiranda** [comment]
same issue here after ipfs upgrade in laptop. go-ipfs moved from v0.10 to v0.11 . I'll try to revert and comment back here

**Comment by rodolfomiranda** [comment]
confirmed, reverting to go-ipfs v0.11, or desktop 0.17 solves the issue

**Comment by KunPengRen** [comment]
Thanks! Solved issue by use desktop version ipfs.
