### ISSUE TITLE
Missing DID READ operation in Sidetree v1.0.0 spec.

### ISSUE THREAD

**Issue by georgejpadayatti** [decentralized-identity/sidetree#1181]
Am I missing something here, it seems the READ (or DID resolve) operation is not present in Sidetree spec -   https://identity.foundation/sidetree/spec/#did-operations

**Comment by csuwildcat** [comment]
DID Operations are modifications to the PKI state of a DID, so resolution isn't an operation the that sense. There is a separate Resolution section that describes the process of resolving a DID from the operations: https://identity.foundation/sidetree/spec/#resolution
