### ISSUE TITLE
Long-Form DID  & Short-Form DID Identity ambiguity 

### ISSUE THREAD

**Issue by mineme0110** [decentralized-identity/sidetree#1211]
Context & Problem

The format of Long-Form DID URI as defined in the spec (https://identity.foundation/sidetree/spec/#long-form-did-uris) 
is 
"did:METHOD:did-suffix:long-form-suffix-data". 

However, this does not align with the W3C specification for DIDs (https://www.w3.org/TR/did-core/#did-syntax)
 which states that the format of a DID is 
"did: method-name :method-specific-id". 

This creates ambiguity as the Long-Form format includes additional data while the W3C specification 
has method-specific-id . which in this case will  include both  did suffix(short-form) and long-form did URI 
(did-suffix : long-form-suffix-data )

LongForm of did identity did = did:METHOD:did-suffi:long-form-suffix-data
Shortform did identity did =  did:METHOD:did-suffix
So these 2 are different did's now or in other words 2 different identities  
Therefore, it is important to clarify whether a Long-Form DID URI is a separate identity 
or if it is the same as a  short form of DID

**Comment by csuwildcat** [comment]
You're allowed to have more segments, the spec only defines the first 3.

**Comment by mineme0110** [comment]
My point is the method-specific-id part in the did syntax make the did identifier 
So if I use long-form did as identifier   and then I switch to the short-form did later
So now I have 2 identity short-form and long-form.  
e.g 
did:method:123:xyz
did:method:123

**Comment by csuwildcat** [comment]
It's still just one logical ID, and it is capable of this because Sidetree utilizes the canonicalId/equivalentId capabilities defined in the spec that are provided to unify different forms of the same logical ID:

Equivalent IDs: https://www.w3.org/TR/did-core/#dfn-equivalentid

Canonical ID: https://www.w3.org/TR/did-core/#dfn-canonicalid

**Comment by thehenrytsai** [comment]
@mineme0110, if you look at `equivalentId` in the resolution document under `didDocumentMetadata`, you will see that it's always the short-form. It is definitely not the most ideal in terms of simplicity, open to suggestions.

**Comment by decentralgabe** [comment]
Correct according to the spec. Pending close.

**Comment by Craeckie** [comment]
I was also confused about the structure of the Long-Form DID, but the spec defines:
```
method-specific-id = *( *idchar ":" ) 1*idchar`
idchar             = ALPHA / DIGIT / "." / "-" / "_" / pct-encoded
```
This means, that in the long form the first `*idchar` is the normal suffix and `1*idchar` is the encoded DID document (`1*` means 1 or more characters: https://www.rfc-editor.org/rfc/rfc5234#section-3.6)

So the Long-Form DID is actually spec compliant.
