### ISSUE TITLE
Anchor File modifications for light node support

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#144]
In order to enable both faster boot and support for more efficient light nodes, the following changes are proposed:

1. Create a new property in the Anchor File called `dids`, and let the value be an array of all the DIDs the anchoring party has included in the operation batch file.
2. Change processing logic to use this new array of declared DIDs to match to the op batch file 1:1 with the indexes declared in the Anchor File DID array.

**Comment by OR13** [comment]
This seems very necessary. We have a browser implementation of `element` that currently has to download every anchorFile and every batchFile before constructing the full tree. This won't ever work at scale, and it would be a shame to loose the ability to resolve a did fully in a browser, for cases where the batchFile size is bounded appropriately. 

Here is a link to our naive but working implementation of sync:

https://github.com/decentralized-identity/element/blob/master/packages/element-lib/src/func/syncFromBlockNumber.js

It would be super awesome to be able to filter these arrays by the did I care about, and save on lots of network requests.

**Comment by thehenrytsai** [comment]
Implemented in 00a28e85c4a06199fb49ba1e4521a2a74b88dd6d
