### ISSUE TITLE
Investigate constant size accumulator scheme for proof of DID op inclusion

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#145]
In order to reduce the processing required for a light node to evaluate DID inclusion, investigate the feasibility of adding a constant size aggregated signature to the Anchor File composed of the signatures from each DID owner declared in the Anchor File DID array.

**Comment by OR13** [comment]
related reading for those interested: https://medium.com/@sergey_nog/how-not-to-use-aggregate-signatures-in-your-blockchain-63e05be2cbbe

**Comment by csuwildcat** [comment]
I met with MSR and a better course we agreed on was to use a cryptographic accumulator that are included in a single accumulator proof by the Batch Writer at blockchain txn insertion time. I will work to provide a set of possible constructions that have the best set of performance trade-offs and post back here when I know more.

**Comment by isaacJChen** [comment]
Will not fix.
