### ISSUE TITLE
DID Document `publicKey` element must contain `controller` field per DID spec

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#165]
Follow the DID spec such that `controller` will be a required field in the returned DID Document.

**Comment by mudiali** [comment]
The controller field for the publicKey section is supposed to point to the owner did (https://w3c.github.io/did-core/#public-keys). When registering the doc, the client may not actually have the did id to populate in there. 

So it probably makes sense for the node to add that field during resolution. So the protocol can block the clients from putting any value in there. @csuwildcat we probably want to update the section 5.3 (https://w3c.github.io/did-core/#public-keys) with a note saying that the individual methods may introduce an intermediate state where the controller value is not present. It would be similar to the NOTE section 5.2 which is:

> DID method specifications MAY create intermediate representations of a DID document that do not contain the id key, such as when a DID resolver is performing resolution. However, the fully resolved DID document MUST contain a valid id property.

**Comment by csuwildcat** [comment]
Why do we think a spec change is required here? The DID spec does not mandate any specific properties, values, or structures on the internal operation data of Methods, only the resolved documents.

**Comment by mudiali** [comment]
@csuwildcat I would think that the update is needed for the same reason that we have an existing note in section 5.2.
