### ISSUE TITLE
Remove concept of 'operation number' in update operation payload

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#172]

**Comment by OR13** [comment]
Adding a bit of color here, I think the reason this is OK is the `previousOperationHash` makes `operationNumber` redundant.

`operationNumber` is only referenced a few places, should be an easy fix: https://github.com/decentralized-identity/sidetree/search?q=operationNumber&unscoped_q=operationNumber

**Comment by thehenrytsai** [comment]
Addressed in 0bdc44367eef752c844dbc6428eefc254f905c7c.
