### ISSUE TITLE
Rename `putBatch` to `put`, and `processBatch` to `process`

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#177]
The concern here is that the term "batch" here is not the same as the "operation batch" or "batch file" being used.

**Comment by Atul9** [comment]
Hi @thehenrytsai In `tests/mocks/MockOperationStore.ts` MockOperationStore already has `put` as a private method. On renaming all occurences of `putBatch` to `put` and running tests I get - 
`Property 'put' is private in type 'MockOperationStore' but not in type 'OperationStore'` 
Please suggest what should `private method put` be renamed to

**Comment by thehenrytsai** [comment]
Use `insert`.

**Comment by Atul9** [comment]
@thehenrytsai I have opened up a PR https://github.com/decentralized-identity/sidetree-core/pull/190, please review
