### ISSUE TITLE
Receipts == proof ?

### ISSUE THREAD

**Issue by llorllale** [decentralized-identity/sidetree#186]
Are we confusing the terms "receipt" with "proof"?

"Receipt" is used throughout the protocol spec and in the code. This receipt structure looks like a merkle proof would, and in the bitcoin world, the proof is *verified* by a light node (ie. a "client"). Using the term "receipt" implies that this structure is delivered to the client as a direct result of a transaction, ie. in the same request-response cycle. This clearly doesn't make sense, as the batch needs to be cut before a merkle tree can be finalized, and this work is performed in the background.

So I don't understand 
* why we're using the term "receipt"
* why `MerkleTree.ts` implements a (unused) `prove()` method

**Comment by csuwildcat** [comment]
It is just a sub-feature present in the case that you want to more quickly validate a given op state was present in an op batch, and could aid in fast resolution schemes.

**Comment by csuwildcat** [comment]
To be clear: no part of the protocol relies on Merkle Tree anchoring proofs to operate.

**Comment by OR13** [comment]
agree its a bit confusing... The idea is that some light client might use it in the future, but without integration tests, its not obvious how.

FWIW we implemented a simple integration test for it here:

https://github.com/decentralized-identity/element/blob/master/packages/element-lib/src/func/__tests__/getOperationReceiptFromBatchFile.spec.js

The formatting and behavior might not match sidetree-core exactly, but this is our attempt at reasoning about its use. 

There was recently some discussion regarding this, i think the idea is to imagine you are getting all anchorFiles and batchFiles at once from some "bootnode", and want to validate them against the chain data, a client can generate a receipt for a given operation and check it against the root in the anchorFile and match the anchorFile hash to the ledger. This allows for batchFiles to be loaded from some source other than IPFS, and yet operations can still be validated.. or at least thats my understanding. @csuwildcat @Therecanbeonlyone1969  did I get this right?

**Comment by csuwildcat** [comment]
@OR13 I think your response is indicative of another feature, fast boot via alternative anchor/batch retrieval, that should exist in the future, but a bit different than the OP's question. The receipt(s) here could be useful if a client with no node at all wanted to query many ION nodes to get a DID's state, and they responded with states that included proofs, as described here: https://github.com/decentralized-identity/sidetree/issues/206

**Comment by thehenrytsai** [comment]
Final notes before closing:

1. Main protocol does NOT rely on the Merkle root to operate.
1. The `receipt` and `prove` methods found are currently not used.
1. As correctly observed, receipt cannot be provided in the same request-response cycle, it was always envisaged to be returned as subsequent request, perhaps a dedicated API or service.
1. The usefulness of the Merkle root is still being discussed but since it is off chain and cheap to include it, we do.

I have updated the protocol documentation capturing the above in commit de0c42b2550cd5fe3a020d0b6eaee40c2d7a5f29, please do open new issues relating to this if you see them.
