### ISSUE TITLE
docker-compose outdated (no-longer works)

### ISSUE THREAD

**Issue by vanjan** [decentralized-identity/sidetree#205]
Running `docker-compose build sidetree-bitcoin` fails with the following error:
```
...
Step 10/26 : RUN npm config set package-lock false &&     npm install &&     npm run build
 ---> Running in a090592d2362
...
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t ssh://git@github.com/hugomrdias/concat-stream.git
npm ERR!
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-05-21T14_10_12_631Z-debug.log
ERROR: Service 'sidetree-bitcoin' failed to build: The command '/bin/sh -c npm config set package-lock false &&     npm install &&     npm run build' returned a non-zero code: 1
```

not sure if that's related, but why is package lock being ignored with `npm config set package-lock false`?

**Comment by thehenrytsai** [comment]
Hi @vanjan,

We are in the final stage of revamping the implementation of the Sidetree-Bitcoin service, after which docker-compose will need to be updated accordingly. Please stay put.

**Comment by thehenrytsai** [comment]
Need to update the docker files according to the Sidetree Bitcoin microservice revamp that uses `bcoin`.

**Comment by thehenrytsai** [comment]
This repo no longer has reference code for spinning up all 3 microservices. For an example of how the 3 microservices are spun up, see [ION](https://github.com/decentralized-identity/ion). ION also has [dockercompose support](https://github.com/decentralized-identity/ion/tree/master/docker).
