### ISSUE TITLE
Add ability to fetch receipts for a DID in REST interface

### ISSUE THREAD

**Issue by christianlundkvist** [decentralized-identity/sidetree#206]
Right now the REST interface will return the complete new DID doc when requesting the DID doc for a specific DID. This makes it hard to independently verify the correctness of the DID doc.

If we had the ability to also fetch the complete history of DID operations in the form of receipts then the end user could validate that the correct keys were used to sign all updates from the original DID document. The end user could also verify that the operations are included in past batches on the blockchain.

This receipt data could be included in the main API that fetches a DID doc or alternatively in a separate interface.

**Comment by OR13** [comment]
Closing, we don't support this anymore.
