### ISSUE TITLE
Design and implement per-op fee calculation algorithm

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#216]

**Comment by csuwildcat** [comment]
@arvinda when you have your write-up ready, can you publish the text and relevant data here in this Issue? I want to make sure the community can view our findings and has an opportunity to review our plan.

**Comment by csuwildcat** [comment]
@arvinda can you post about the status of the per-op fee implemention you've written?

**Comment by mudiali** [comment]
The algorithm part is done. We are going to use the issue #25 to track rest of the changes for the proof of fee.
