### ISSUE TITLE
Unit Tests for Blockchain, and CAS Clients

### ISSUE THREAD

**Issue by sylar217** [decentralized-identity/sidetree#22]
Use mocking libraries to mock the REST API calls to blockchain and CAS calls and validate the functionality

**Comment by OR13** [comment]
Related, I pulled down the latest and the current tests were failing (the did document id was not correct after the create request).

I fixed the test and added travis ci to my fork.

Having CI tests will really help encourage contributions and increate confidence that contributors are not breaking things.

https://travis-ci.org/transmute-industries/sidetree-core/builds/442307014

I'm not a member of this github org yet, but if someone can turn on travis ci for this repo, I'm happy to open a PR with the passing tests and ci changes.

**Comment by OR13** [comment]
I'd be interested in adding these tests once some CI system is hooked up.

**Comment by OR13** [comment]
@thehenrytsai Can I open a pull request that adds Travis CI and runs the current test suite?

**Comment by thehenrytsai** [comment]
@OR13, yes please! I can setup Travis CI if needed.

**Comment by OR13** [comment]
@thehenrytsai https://github.com/decentralized-identity/sidetree-core/pull/41

Done.

**Comment by OR13** [comment]
I'm not exactly sure what format we want to be using for mocking these clients, but here is one approach:

https://github.com/transmute-industries/sidetree-core/commit/5f2515f4450d8a37cc963dcfe8fa373db2f225ff

Happy open a PR or restructure these tests based on feedback.

**Comment by thehenrytsai** [comment]
Thanks @OR13, I was not able to repro the unit test issue on a separate Windows environment, but just managed to repro on a mac, will debug and provide a fix, then merge in your PR. Then I'll look at the branch for client mocking code.

**Comment by thehenrytsai** [comment]
Turned out to be test JSON file stored on Windows vs Linux being different which causes the buffer to be different (Windows uses \n\r, Linus uses \n). Will submit a fix.

**Comment by thehenrytsai** [comment]
Hi @OR13, your pull request on Travis CI is merged, thanks again!

I took a look at your approach for mocking the CAS and blockchain servers and they look fine for the purpose of unit testing. Would be great if you can open a PR. 

Regarding the exact response schema, they are already intended to be somewhat chain agnostic, and are defined in the [implementation documentation](https://github.com/decentralized-identity/sidetree-core/blob/master/docs/implementation.md) under Blockchain/CAS REST API sections. They are subject to change as we refine the design and implementation, but you can follow that for now.

I've made some comments on your current commits.

**Comment by thehenrytsai** [comment]
Much more unit tests have been added since then. Also added #212 to boost code coverage to near 100%.
