### ISSUE TITLE
Implement better method of fetching IPFS content size without downloading it

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#223]
Currently `cumulativeSize` returned by `IPFS.object.stat()` is used but it is not precise, replace the implementation.

**Comment by csuwildcat** [comment]
I have a request for feedback in with my buddy at Protocol Labs (devs of IPFS)

**Comment by thehenrytsai** [comment]
https://github.com/libp2p/interface-peer-discovery#modules-that-implement-the-interface
https://github.com/ipfs/js-ipfs-unixfs-exporter#example
https://github.com/ipfs/js-ipfs/blob/master/src/core/components/cat.js#L28

**Comment by csuwildcat** [comment]
I just want to make sure we remain aware that any metadata convenience methods IPFS provides to report the size before download are not trustable, as the file creator/sender can misreport the values. The only thing that it will catch is files that honestly state they are too large, so all the code to check the real size is still required as we do the actual download.

**Comment by isaacJChen** [comment]
@csuwildcat Yes. We will check the reported size: if exceeds limit, skips download || if within limit, start downloading by chunks, for each chunk, check current cumulative size and stops if size exceeded.
