### ISSUE TITLE
`/firstValid` call failing under certain conditions

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#228]
From @logangirvin:

Sidetree Core issues a `/firstValid` request to its Bitcoin service module, which returns 400 bad_request. There are two potential errors that need to be addressed:

The first has already been resolved in prod: The Bitcoin service failing to read the request in full

The second is that the request may be formatted incorrectly. Need to write a test to fully verify the format.

**Comment by thehenrytsai** [comment]
Fixed in 8f7b00d7b32d4b6d9fb97bfce6c121eaefcf7cb8
