### ISSUE TITLE
Protocol rules for assigning a specific function/purpose to keys

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#229]
Per the DID Spec: https://w3c-ccg.github.io/did-spec/#example-5-various-public-keys

Public Keys must have an `id` property.

Unfortunately, the examples like  `did:example:123456789abcdefghi#keys-2`, don't provide a clear method for a key holder to determine an `id` for the key in a clear way, and thus, in order to determine if a key is present often times the properties of the key must be compared... I suggest we be stricter in a way that helps wallet developers and users. 

I'm borrowing from a couple of projects here:

https://github.com/decentralized-identity/github-did/blob/master/packages/lib/src/v2/func/getPublicKeyFromDIDDoc.js

https://github.com/transmute-industries/did-wallet/blob/master/src/keyToKID.js

I propose that a sidetree public key have and id constructed as follows:

`did:example:123#kid=base64Url(sha256(
  "publicKeyPem" | 
  "publicKeyJwk" | 
  "publicKeyHex" | 
  "publicKeyBase64" | 
  "publicKeyBase58" | 
  "publicKeyMultibase"))`

This will also allow wallets / other systems to index key pairs by public key, which will then aid in signing operations with the correct key.

as a wallet system interacting with sidetree, you will be wanting to retrieve keys easily in constant time, and be able to distinguish between key types / (signature purposes), such a update / recovery.

**Comment by csuwildcat** [comment]
Perhaps we can title this Issue differently, assuming this is squarely about how to mark a key for a certain use/role? I would suggest something like "Protocol rules for assigning a specific function/purpose to keys"

If this is the desire, my opinion is that we should add a property called `function` or `purpose` and recognize a set of values (for example: `update`, `signing`, `encryption`, `recovery`, etc.) that can be added to an array assigned to that property.

**Comment by OR13** [comment]
For example:

```
{
    "id": "did:example:123#kid=456",
    "type": "RsaVerificationKey2018",
    "controller": "did:example:123",
    "purpose": "recovery",
    "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----\r\n"
}
```

I think the note about the `id` property is more of a useful convention (optional), but we do need a way to know that a given key is the recovery key, since only that key can be used in `recover` and `delete` operations.

**Comment by OR13** [comment]
It may be too complex here, but "update" is probably too permissive.

https://medium.com/@markherhold/validating-json-patch-requests-44ca5981a7fc

I can see wanting to allow a key that only is allowed to update a specific service...

For example, I may want to allow an agent to update its service in my did document, but make no other changes to my did document.

This is a special case of validating a json patch and ensuring that only an update signed with the appropriate purpose or a more privileged key is making the update.... 

Could be implemented with some thing like:

```
{
    "id": "did:example:123#kid=456",
    "type": "Secp256k1VerificationKey2018",
    "controller": "did:example:123",
    "purpose": "validatedUpdate",
    "validationSchema": "https://schema.org/updateSocialWebInboxService",
    "publicKeyHex": "029a4774d543094deaf342663ae672728e12f03b3b6d9816b0b79995fade0fab23"
}
```

for updating something like:

```
{
    "id": "did:example:123456789abcdefghi#inbox",
    "type": "SocialWebInboxService",
    "serviceEndpoint": "https://social.example.com/83hfh37dj",
    "description": "My public social inbox",
    "spamCost": {
      "amount": "0.50",
      "currency": "USD"
    }
  }
```

Resolving schemas from URLs would likely be too expensive... they could be embedded, or there could be a set of schemas which were shipped with the protocol.

See also:

https://ajv.js.org/#merge-and-patch-keywords

**Comment by OR13** [comment]
super seeded by: https://github.com/decentralized-identity/sidetree/issues/449
