### ISSUE TITLE
Service 'sidetree-bitcore' failed to build

### ISSUE THREAD

**Issue by lucafra23** [decentralized-identity/sidetree#234]
After running the command "sudo docker-compose build", inside the Sidetree folder, I got the following error:

ERROR: Service 'sidetree-bitcore' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder306919953/lib/bitcored-extension: no such file or directory

I tried to look for the file, but I could not find it..

Any ideas on how to fix this?

Thanks

**Comment by thehenrytsai** [comment]
This is a known issue: https://github.com/decentralized-identity/sidetree/issues/205, unfortunately I am stretched thin right now to tackle this.

Please consider using this [setup guide](https://github.com/decentralized-identity/ion/blob/master/install-guide.md) for spinning up your own node.

Adding @rado0x54, maybe he can help since he was the original docker compose contributor .

**Comment by cboscolo** [comment]
@thehenrytsai am I correct in understanding that you have changed from using `bitcore` to `bcoin`?
It looks like the setup guide you mention described `bcoin` but the docker-compose is trying to build `bitcore`.  In the case would the proper fix be to update the microservice to use `bcoin`?

**Comment by adityaishan** [comment]
I am trying to do the same things for this repository: [https://github.com/decentralized-identity/sidetree/blob/master/docs/docker.md]. After running the docker-compose.yml file it is giving this 

**Error:** 
Step 8/18 : COPY ./lib/bitcored-extension ./node_modules/sidetree
ERROR: Service 'sidetree-bitcore' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder789845024/lib/bitcored-extension: no such file or directory

**Comment by thehenrytsai** [comment]
Will close this bug and let issue #205 track the work on updating the docker-compose. We have since moved away from both bitcore and bcoin and used the official bitcoin client instead.
