### ISSUE TITLE
Consider removing didUniqueSuffixes from Anchor file replacing with bloom filter

### ISSUE THREAD

**Issue by cboscolo** [decentralized-identity/sidetree#237]
_Disclaimer: I apologize in advance if this idea has already been considered, or if my lack of technical understanding of the architecture lead me down a wrong path._

The gist of this idea is driven by the desire to build a light client that only needs to validate a relatively small number DIDs in a time and space-efficient manner, but wants to do so without trusting on a full node. It also assumes a light node that can keep up with the updates.  (In the case of ION, it means processing an anchor file every 10 minutes which should be easy.)

The idea is to replace the `didUniqueSuffixes` stored in the anchor file with a bloom filter.  The `didUniqueSuffixes` would be added to the batch file to further optimize whether or not a client needs to process that batch (again assuming it is only interested in a handful of DIDs)

One other optimization to consider is to make didUniqueSuffixes a map (with Nil values) instead of an array. In this way after JSON parsing, individual DID lookups would be a map lookup instead of array search.

One final but optional change if we remove `didUniqueSuffixes` from the anchor file is to add a DID count, so the light client can predict the size of the batch file it will need to process.  (For example, if DID count is 3, and it could cap the batch file download to 3*MAX_OPERATION_SIZE+JSON_OVERHEAD)

Reasons this makes a light client more robust:
- With this change, the anchor file remains extremely small and a fixed size regardless of the number of DIDs in the batch.
- For light clients that only care about tracking the state of a handful of DIDs, this change makes it much more efficient to know which batch files to process. (Assuming an optimized bloom filter.)

**Comment by OR13** [comment]
These are excellent ideas, @cboscolo your intuition is correct, and a bloom filter would be faster for lookups.

**Comment by cboscolo** [comment]
After a little back of the napkin calculation (which I should have done first...), I'm starting doubt if this is worth it. In rough numbers, if avg DID suffix length is 32 bytes, 
32*8192 = 262,144 bytes per anchor file if they are all full of DIDs. (Which may happen at peak Sidetree use, but not in the early days.)
vs.
A Bloom filter with 2% false positive for 8192 elements would be about 8,140 bytes per anchor file.

**Comment by AlexITC** [comment]
If what you are interested is reducing the space, following [BIP-158](https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki) may be a better option, the Golomb Codec Set is like a Bloom Filter but it has smaller size with slightly slower query times.

**Comment by csuwildcat** [comment]
We will definitely move from the present array [] of DID Suffixes to a map {}, in support of https://github.com/decentralized-identity/sidetree/issues/252. Issue 252 raises a more important overarching issue that afflicts any simple structure that contains no proof of validity: whether or not it is an array, object, or bloom filter doesn't prove a valid, non-spam DID op is likely in the batch. The fix for 252 addresses this, and though an actual map with the commitment values described in 252 is larger. To have both properties in one, you would need to do something like pairing the DID Suffixes together with the revealed commitment values (detailed in 252) when creating the filter.
