### ISSUE TITLE
Operation size limit and its impact on key types

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#242]
The size of ops, and data contained within them, has a direct impact on network operators. The protocol limit operation size to 1-2k and will soon be enhanced with stricter content validation to ensure that scale boundaries are maintained. One of the impacts the operation size limit has on the network is the types of keys that can be embedded in an operation. Directly embedding a (currently) secure RSA 2048 public key violates the limit and would be deemed an invalid operation. Here is a proposal for how to deal with keys and their role in the protocol:

1. We should limit the protocol-authoritative key types (keys that can perform DID ops) to a defined set. (secp256k1/ED25519, both?)
2. Key types not in that defined set could still be included in a DID op, if they don't exceed the size limit.
--BUT--
3. If a key type does exceed the size limit, you can add a key to a DID op for use in things outside of intra-protocol op signing by including a hash of the desired public key.

For example: if you wanted to use an RSA key that you included in your DID by hash reference, it would mean you'd need to add one more detail to DID exchanges and communications if you wanted to use the larger RSA key type: send the RSA public key along with a handshake or signed object so the receiver can match it against its hash and validate it.

How do people feel about this compromise?

**Comment by cboscolo** [comment]
A 2048 bit RSA public key in PEM format is 451 bytes.  I would rather just increase the operation max size by 500 bytes than add more special-case logic.

**Comment by csuwildcat** [comment]
@thehenrytsai - what @cboscolo mentioned above is probably a good stopgap, given pub key PEM is already part of the DID Doc spec. I still like the idea of key/key list hash representations of control-proving material, because it opens up use of key material and proofs for use cases that do not require verbose, protocol-reliant public values in the DID Doc.

**Comment by csuwildcat** [comment]
Given the ability to include an RSA key in a truncated form, as Chris noted, I propose that secp256k1 keys should be the only protocol-active key type, meaning they are the only type that can sign an op (to minimize complexity of the implementation). Obviously you'll still be able to add other key types to your DID Doc, but they just aren't used for op signing. Also, I am proposing that we stick to a strict 1k max size for ops, which will admittedly be a forcing function for using more compact key types, but que sera sera.

**Comment by csuwildcat** [comment]
I believe we've settled this, so let me know if it needs to remain open, else I'll close it next week.
