### ISSUE TITLE
Is bitcoinWalletImportString valid? Consider using testnet key generated below: cUe2b8s47YKbWw9sb9VJWXXucetDLHHz5sUbhk9EJ8R2GMr5DjpR

### ISSUE THREAD

**Issue by lucafra23** [decentralized-identity/sidetree#243]
I have set the bitcoinWalletImportString of the bitcoin-config.json with the value of the private key of my bitcoin wallet.

Also, I tried to use the testnet private key generated from the sidetone script.

Still I get the same logs and errors:

Is bitcoinWalletImportString valid? Consider using testnet key generated below:
cUe2b8s47YKbWw9sb9VJWXXucetDLHHz5sUbhk9EJ8R2GMr5DjpR
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ion@0.2.0 bitcoin: `node dist/src/bitcoin.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ion@0.2.0 bitcoin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Can somebody help with this issue?
Thanks

**Comment by AlexITC** [comment]
I have no issues on the latest commit (4a76bb5b099ce3eaddcd7dc63200bb1745f7d03e), it is very likely that you forget to rebuild the config before running the app (`npm run build`) which needs to be executed after changing the json files.

**Comment by lucafra23** [comment]
Actually I already rebuilt the app after changing the config files, but I still get the same error logs.

Could the problem be that I need to run the instance for at least 6hours in order for it to sync with the bitcoin testnet?

I imagine that if I used the private key of a recently created wallet, the instance will need time to witness the recent block where the wallet is being created.Still, even if I put the private key for the testing purpose suggested by the log, I get the same error log

**Comment by lucafra23** [comment]
This is the specific log I get:

14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/snap/node/2252/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid ion@0.2.0
16 verbose cwd /home/ubuntu/bcoin/ion
17 verbose Linux 4.15.0-1032-aws
18 verbose argv "/snap/node/2252/bin/node" "/snap/node/2252/bin/npm" "run" "bitcoin"
19 verbose node v10.16.0
20 verbose npm  v6.9.0
21 error code ELIFECYCLE
22 error errno 1
23 error ion@0.2.0 bitcoin: `node dist/src/bitcoin.js`
23 error Exit status 1
24 error Failed at the ion@0.2.0 bitcoin script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by lucafra23** [comment]
This is the full log I get:

0 info it worked if it ends with ok
1 verbose cli [ '/snap/node/2315/bin/node',
1 verbose cli   '/snap/node/2315/bin/npm',
1 verbose cli   'run',
1 verbose cli   'bitcoin' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prebitcoin', 'bitcoin', 'postbitcoin' ]
5 info lifecycle ion@0.2.0~prebitcoin: ion@0.2.0
6 info lifecycle ion@0.2.0~bitcoin: ion@0.2.0
7 verbose lifecycle ion@0.2.0~bitcoin: unsafe-perm in lifecycle true
8 verbose lifecycle ion@0.2.0~bitcoin: PATH: /snap/node/2315/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/bcoin/ion/node_modules/.bin:/snap/node/$
9 verbose lifecycle ion@0.2.0~bitcoin: CWD: /home/ubuntu/bcoin/ion
10 silly lifecycle ion@0.2.0~bitcoin: Args: [ '-c', 'node dist/src/bitcoin.js' ]
11 silly lifecycle ion@0.2.0~bitcoin: Returned: code: 1  signal: null
12 info lifecycle ion@0.2.0~bitcoin: Failed to exec bitcoin script
13 verbose stack Error: ion@0.2.0 bitcoin: `node dist/src/bitcoin.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/snap/node/2315/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/snap/node/2315/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ion@0.2.0
15 verbose cwd /home/ubuntu/bcoin/ion
16 verbose Linux 4.15.0-1041-aws
17 verbose argv "/snap/node/2315/bin/node" "/snap/node/2315/bin/npm" "run" "bitcoin"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error ion@0.2.0 bitcoin: `node dist/src/bitcoin.js`
22 error Exit status 1
23 error Failed at the ion@0.2.0 bitcoin script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



I always run " npm run build" everytime I change the config files..

It seems to me it's a script error but I can't find it

**Comment by thehenrytsai** [comment]
@lucafra23, v0.3.0 have since moved over to using Bitcoin Core client instead of BCoin. Are you still having this problem?

**Comment by csuwildcat** [comment]
Please provide feedback as to the status of this Issue pursuant to Henry's note about the 0.3.0 changes, so we can understand if this is still an active concern.

**Comment by lucafra23** [comment]
Hi All, when setting up the project manually, I still have the same "bitcoinWalletImportString " problem mentioned before. 

About the docker issue, i get the same problem as before:
"ERROR: Service 'sidetree-bitcore' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder596920231/lib/bitcored-extension: no such file or directory"

Am I missing something in the set-up?

Thanks

**Comment by lucafra23** [comment]
It seems the AWS instance I was using was too small, using a t2-large instance made it work.The problem Is fixed now
