### ISSUE TITLE
Revisit resolution using Initial DID Document

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#256]
Currently resolution using initial DID Document uses the current blockchain time for deciding hash algorithm to use for generating the DID.

However this implies that either:
* This resolution method is only intended for bootstrapping during the initial registration phase, thus this resolution method cannot be reliably used long term because new hashing algorithms can be introduced; or
* We need to have a reliable method for selecting hashing algorithm for this type of resolution.

**Comment by csuwildcat** [comment]
What about adding leading bytes before the DID Suffix portion of the string?
