### ISSUE TITLE
Use a JSON map instead of array in operation file

### ISSUE THREAD

**Issue by cboscolo** [decentralized-identity/sidetree#259]
Since there can only be one DID operation per transaction.
Rather than using JSON array for storing the DIDs in the batch, use a map with DID suffix as the key, and {} as the value? (I referenced this in the optimization ticket I wrote. (#237)

As a map, it's easy to check for the existence of one particular DID, with little loss of efficiency iterating over all keys, and no extra logic is needed to figure out if there are dupes. Thus, the only check needed is to ensure the number of entries in the map equals the number of operations in the batch.

This idea was originally proposed in this thread: #173

**Comment by csuwildcat** [comment]
Closing this, as it will soon be added via implementation of other Issues.
