### ISSUE TITLE
Use multihash throughout code as described by Sidetree protocol

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#26]

**Comment by csuwildcat** [comment]
Was this is the thing that degraded perf a lot, related to the base encoding type? I thought I remembered there being some issue with 58 vs 64

**Comment by thehenrytsai** [comment]
No, this is not. The library we used for base58 encoding was degrading the perf by a lot, but we have since moved away from it to base64url.

**Comment by thehenrytsai** [comment]
Implemented in 445709a6202c898fb8be5899c755ac86524f1975.
