### ISSUE TITLE
sidetreeTransactionPrefix mismatch

### ISSUE THREAD

**Issue by jlopp** [decentralized-identity/sidetree#260]
It's unclear to me which prefix is correct; the setup script creates a json config with the prefix "sidetree:"
https://github.com/decentralized-identity/sidetree/blob/master/lib/bitcoin/setup.sh#L78

While the config in the ion repo shows it to be "ion:"
https://github.com/decentralized-identity/ion/blob/master/json/bitcoin-config.json#L7

**Comment by cboscolo** [comment]
They are both correct. My understanding is that:
`sidetree` is the generic blockchain agnostic implementation.  Think of it as the base class from which specific blockchain-specific versions are derived.
`ion` is a specific implementation of sidetree that uses the BTC ledger.

There should never be DIDs used in the wild with a method of `sidetree`.

**Comment by jlopp** [comment]
Hmmm then perhaps the setup shell script should generate that line to be more like:

`"sidetreeTransactionPrefix": "[FILL THIS IN!]:",`

**Comment by thehenrytsai** [comment]
@cboscolo is right, and @jlopp your suggestion is valid, I will make the change in the next commit.

**Comment by thehenrytsai** [comment]
Change committed.
