### ISSUE TITLE
Replace JSON patch with strict update payload schema

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#262]

**Comment by OR13** [comment]
Why do we need to replace the patch, why not apply some validation to it instead?

I included some comments here:

https://github.com/decentralized-identity/sidetree/issues/229

**Comment by csuwildcat** [comment]
I would venture a guess and say that we want to validate before the merge of a delta, meaning we need to strictly control and evaluate delta contents. This might be hard to do in a super specific and efficient way without some custom code. Henry, does that sound about right?

**Comment by thehenrytsai** [comment]
@csuwildcat yes that's correct. I am now in the process of adding validation logic to the update payload at the observing time, upon until now it has just been "return true" regardless of what is in the patch. Validating a free-form JSON patch to meet the DID spec would be quite difficult if not at least tedious and error-prone IMO. Having a stricter schema make this validation logic a lot simpler (at least more readable).

@OR13's request on labeling keys in #229 is still valid and related, and will be looked at as its own issue.

I will upload a link to the proposed update operation API/schema change.

**Comment by thehenrytsai** [comment]
https://github.com/decentralized-identity/sidetree/blob/henrytsai/120/docs/protocol.md#update-payload-schema

Note that we will need a better way at surfacing/documenting the allowed key algorithms and and supported format combination(s).

For now I am just listing the minimal set as a start.

Same goes with `serviceType`, we can add to the allowed list then what is currently allowed.

**Comment by thehenrytsai** [comment]
Implemented in 2bca504dae9a36de6dc7330bc5baa1a2c628050a.
