### ISSUE TITLE
Implement economic locking as a prerequisite for writing larger batches

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#271]
Once the Proof of Fee algos/code are in place (which shouldn't be too long now), there will be a network-determined cost for individual operations set across block-windows (based on a deterministic calculation nodes can all use to get the right answer) which will force writers to pay a txn fee in accordance with the size of the op batch they seek to write.

When a fee variable exists in the system, we may have another interesting tool at our disposal: a form of staking - but to be clear, not Proof of Stake or some consensus scheme of that name. Imagine that the ability to write very large batches and have them be seen as valid required you to 'stake' a much larger sum locked in an on-chain txn and held for some time before you could use it to write one batch per block from the locked sum. The larger the batches you sought to write, the longer you would need to leave that 'staked' value untouched before you could actually use it to write batches, and even then, just one per block at the size-level you staked to achieve. This would follow a curve, so that people writing very small batches may not stake anything or wait at all, whereas the staked cost/time would increase a ton as you ascended into larger batch sizes that approached the maximum cap.

Here's how it would look:

Let's say the per-op fee variable is the equivalent of $0.001 for the current block-window

- If I wanted to write under 100 ops (just an example number), I wouldn't have to stake and wait at all.
- If I wanted to write a 10,000 op batch, I might need to stake 1 million times the current Proof of Fee rate ($1000), and wait 10 blocks to start using that wallet of op funding value.
- If I wanted to write a 50,000 op batch, I might need to stake 50 million times the current Proof of Fee rate ($50,000), and wait 500 blocks to start using the locked funds for batch writing.

After the lock-up period is over, you can still only write 1 batch per block from that funding txn. Additionally, if the locked funds are moved before or any time after the locking period for anything other than to write a batch, the lock is broken and everything is reset. Any txn that breaks the rules would have its batches ignored. 

The two key outcomes should be:

1. Spammers have to publicly lock up exponentially more $ than it actually costs to generate a massive spike of large batches, which is a huge logistical and feasibility hurdle for the vast majority of attackers.
2. You can 'see spam coming', because the larger the batches you wish to write, the longer the lock time - which could be literally days before you can start writing.

**Comment by OR13** [comment]
I'm a bit concerned about on chain transaction type extensions,  I think the simpler the ledger side of sidetree the better. 

I don't understand how the nodes validate that a given transaction and linked batch are paid for here. The attacker would run their own node, and simply publish the large datasets (there is no write side protection, there is only read side validation).

Honest nodes would process the attackers transactions and see that the attacker node was attempting to exceed its limits, at which point they can decide to drop the transactions or not.

This ticket seems to be asking, can we use reputation to prevent spam attacks, staking being one very popular solution to that problem, but there are other methods as well.

It feels to me that Sidetree Protocol should expose the information needed to design a reputation system for nodes, and potentially establish a lower bound on transaction inclusion to protect users from becoming incapable of self managing, but the questions around pricing of larger transaction batches, windows, etc... These seem to potentially be more tightly coupled to the concept of concrete sidetree implementations like ION or Element.

I do really like the idea of standardizing how sidetree transactions become reputation information about a given private key, that seems valuable in an agnostic manner, I'm not sure the protocol should try to enforce behavior around this, because the cost of using a private key on a blockchain, and blocktime / transaction fees will vary greatly, so it feels like maybe the right place to handle that kind of reputation is at the concrete DID Method implementation layer.

**Comment by csuwildcat** [comment]
@OR13 this isn't about reputation, it's about a spammer having to lock a ton more value on-chain and wait time that corresponds to how large of batches they wish to write. I think you're getting this rather straightforward value-locking imposition with actual reputation systems.

**Comment by cboscolo** [comment]
I don't understand how "locking value" will help prevent spam.  If I'm a BTC hodler, how is this hurting me?
Also doesn't this get in the way of an honest node that received a request to write a bunch of ops?

**Comment by csuwildcat** [comment]
Not sure what you mean. If you're an honest node, you'll pre-lock the
required amount - which for most nodes that aren't doing massive batches,
will not require a lock at all, then do your txn and it'll be accepted by
the greater network.

**Comment by cboscolo** [comment]
Perhaps I don't quite understand how batches are paid for or staked?
(Assuming a BTC chain.) Is the BTC burned to "pay" for a batch?

**Comment by csuwildcat** [comment]
@cboscolo batches are paid for buy paying the per-op fee times the number of ops in the batch, a fee established by a deterministic, network-wide calculation over moving block-windows. The fee is paid by over paying the requisite amount in the fee portion of the on-chain txn that hosts the batch anchor. With this fee variable in hand, we can probably institute other measures, like the one described here, to further shape inbound traffic.

**Comment by cboscolo** [comment]
I think I got it now.
So, the problem I see with this is that there is still a very little cost of performing a spam attack with this mechanism. Using your example numbers, ($50,000 for 500 blocks) I could borrow that money at say 4% interest, and it only cost me $19.02 to start attacking and costs me only $542 per day (plus the ops fees) to continue the attack.
Then when I am done attacking, I get my BTC back and pay the loan back.

**Comment by csuwildcat** [comment]
Sure, you could definitely acquire tens or hundreds of thousands of dollars
to spam a little, if you wanted, but there's two things I'd say in response:

1. You'd have to basically have the system be 95% malicious spam to even be
concerning, because the checkpointing restructuring will enable us to wipe
away most of the spammer's data.
2. This is about spikes, so remember that tens or hundreds of thousands of
dollars locked up buys you the ability to spam a few tens of MBs per block,
because you can only use that locked sum on one txn. To do a spam spike,
you'd need to lock tens of millions dollars across many txns, and even
then, the modulating window function would suppress your spike by limiting
throughput to account for the flow.

**Comment by cboscolo** [comment]
That is chump-change for any large federated identity company or nation-states that wants to demonstrate to the world how fragile sidetree/ion is by mounting such a prolonged attack.

Forcing honest batch writers that got a sudden spike in demand to wait (up to several days) to write the batches is lame, and will likely just lead to dissatisfied users.

I'd much rather we investigate true staking mechanisms where invalid batches cause batch writers to actually lose their stake.

**Comment by csuwildcat** [comment]
I'm still not seeing your point: an honest actor is not blocked just
because some other moron decides to lock up millions of dollars and spend
their time spamming a minority percentage of ops the system processes.
Eventually op price might increase temporarily, but that's a market
function I'm absolutely comfortable with. If you're worried about people
making blockchain txns more expensive, staking doesn't solve it, it's an
attribute of just about any open system.

This makes spamming very difficult for 99.99% of potential spam sources, so
it's a massive win. If we're worried about nation states attacking systems,
there's no magic bullet, they'd be able to impact just about anything that
relies on network connections.

**Comment by cboscolo** [comment]
I thought you were proposing a mechanism where an honest batch writer could write a huge batch by creating a txn with large amounts of BTC, and not touching it for many BTC blocks.
Then after that number of blocks, it can write the huge batch.

**Comment by csuwildcat** [comment]
The proposal is that anyone who wants to write a massive block has to lock
up a size-relative amount of BTC and wait for a size-relative locking
period to start using that locked value for op batches, and even then, one
batch per block per locking txn. This would apply to all writers. Can you
give me a serious use case where an individual needs legitimate, immediate,
0-prerequisite access to blasting the system with 50k ops? My thesis is
that these larger batch sizes would generally be done by companies and
large organizations anyway, who could afford the locking cost/coordination.

**Comment by cboscolo** [comment]
Really?  That actually surprises me.
I suspect like most Internet services, there will be a handful of service providers (like Microsoft) that create DIDs for new users that sign up to use services. I could image someone launches a hot new website or mobile app which on the backend uses one of these service providers. Then image some viral event causes millions of people to learn about this website/app and want to sign up to use it, and there is a sudden influx of legitimate DIDs that need to be issued.

**Comment by csuwildcat** [comment]
Something like under 1000 ops would have no locking requirements, so you'd
always be able to use the system instantly, if that's your concern. But I'm
not sure why having a few orgs who have locked enough to do large batches
could clear the 'op pool' just as Bitcoin clears its mempool.

Remember: DIDs in ION/Sidetree are *immediately usable* even before they
make it into a block, so the actual case of being able to handle and influx
of new DID users isn't really a concern.

**Comment by cboscolo** [comment]
Scenario 2:
Twitter embraces "The W3C DID/VC Way" and allows users to associate a public DID with their Twitter account. With this feature, users can sign comments on another website as proof of authorship. (These are all public forums where public correlation is a feature, not a concern.)

Many millions of users install the Acme Wallet Chrome extension, create a public ION DID and begin to make use of this feature.

Hackers find a bug in the Acme Wallet that exposes the private key of all 10 million users that used this feature on a popular forum website.

All 10 million users need to update their DID at the same time using the backup key of the original DID creation.

**Comment by csuwildcat** [comment]
Sounds like this involves exfiltration of an enclave-locked key, which I'd
argue is highly unlikely. That aside, let's look at the numbers:

Projections we've done show ION can process somewhere in the neighborhood
of 1500 ops per second, meaning you could do about 850k ops per block. If
you needed to clear 10 million ops, you could probably do so in 15 to
low-tens of blocks (depending on the load at the time).
