### ISSUE TITLE
Add "next one-time update token hash" information in the resolved DID Document

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#287]
"last operation hash" this information will be very useful for the DID owner when a new update operation is constructed because the update operation will need to populate the correct `previousOperationHash` value.

**Comment by haardikk21** [comment]
I can take this. To clarify, should we be changing the `DocumentModel` interface to include a `previousOperationHash` field or should we send an object of the form `{ document: didDoc, previousOperationHash: previousOperationHash }` in the resolve request?

**Comment by thehenrytsai** [comment]
If we do it, I would imagine it to be the first (changing document model), but please hold off a little bit, there is currently a discussion that we might just remove `previousOperationHash` as a concept altogether, in which case this bug will no longer be applicable.

**Comment by OR13** [comment]
I agree these things would be useful, I suggest we consider adding a sidetreeMeta section to the did document for both `previousOperationHash`, and OTP values... much easier to use... in element we are constantly querying or calculating these values on the fly to make client updates easy....

**Comment by csuwildcat** [comment]
Why wouldn't this be in the Resolver metadata?

**Comment by csuwildcat** [comment]
Why is this mainnet blocking? This is not even a functional feature, and most wallets will use commitment values that can be deterministically regenerated without any hints. I'm not saying this isn't a possible nice-to-have, but it sure doesn't seem important enough to block mainnet.

**Comment by tplooker** [comment]
Really old, closing as a result, no longer relevant, this now called commit reveal scheme.
