### ISSUE TITLE
Add documentation on release `SemVer` versioning and the meaning of each component.

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#291]
Add implementation documentation on release `SemVer` versioning and the meaning of each component:

Major - Major Protocol Evolution
Protocol advancements so large that warrant a major version increment.

Minor - Forks & Required Upgrades
Critical updates, protocol forking changes, or security patches that require all nodes to upgrade.

Patch - Discretionary Updates
Non-critical, minor changes that do not require nodes to upgrade.

**Comment by OR13** [comment]
almost done.

**Comment by csuwildcat** [comment]
I believe @OR13 finished off most of the content, and I polished the rock a bit in https://github.com/decentralized-identity/sidetree/pull/523, but take a look here and see if this understanding of versioning for the spec/impl. is reflected as desired: https://identity.foundation/sidetree/docs/spec/#version-segment-definitions

**Comment by OR13** [comment]
@csuwildcat IMO this should be closed.
