### ISSUE TITLE
Update the core endpoints to be more RESTful 

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#295]
Currently, either to create/update or resolve a DID, the client must send the request to the root url. e.g. ion.microsoft.com/. To be more RESTful, the server should listen on a noun. E.g. the url to createDID would become ion.microsoft.com/did. To update or resolve a did, the client can send request to ion.microsoft.com/did/<did-id>

**Comment by isaacJChen** [comment]
post and get only. Only change path to include did.
