### ISSUE TITLE
js-IPFS v0.39.0-rc2

### ISSUE THREAD

**Issue by achingbrain** [decentralized-identity/sidetree#314]
There's a new release candidate for `js-IPFS` available - `v0.39.0-rc2`

The good news is we ran the `sidetree` test suite with it installed in CI and they [passed](https://travis-ci.com/ipfs/js-ipfs/jobs/246787281) so there's nothing to do!

You can probably close this issue 😁

**Comment by thehenrytsai** [comment]
#335 tracks updating to the IPFS lib to new version.
