### ISSUE TITLE
Suggestion for distributed key management and recovery. 

### ISSUE THREAD

**Issue by xDanielA** [decentralized-identity/sidetree#318]
Hi all,

Would love to explore if this is something we can incorporate for key signing and recovery for identities. 

https://drive.google.com/file/d/1iWkUlVMk3sJaJh8ZLe3lz5ri_xrJQfrX/view

**Comment by OR13** [comment]
I had a good conversation with these guys after a Capital Factory event. There is some related community work, in particular multisig / threshold crypto for DID Authentication: 

https://github.com/w3c/did-spec/issues/2

@burntorange89 can you add the specific signature mechanisms (with reference implementation links) to this ticket if possible?

When attempting to address the auth ticket above, I started looking at: https://github.com/Turing-Chain/TSSKit-Threshold-Signature-Scheme-Toolkit

But could not figure out how to present the key material needed to propose a JSON format for threshold auth... that is what is required to integrate this. We need a way to represent threshold public keys in a DID Document, and a way to represent a threshold signature.

If both use secp256k1 its possible this could be directly applied to sidetree.

**Comment by CoreyTX** [comment]
Here is some additional research and reference projects that @burntorange89  did for the solution for the communities reference. 

https://www.notion.so/Abstrakt-Digital-Signature-Implementation-bfbcb5cc22b44f7b8991a0ad5af3685c

**Comment by OR13** [comment]
This is stale, you can do this with sidetree... non actionable.
