### ISSUE TITLE
Implement different operation modes (resolver, observer, etc) for the nodes to support different topology

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#319]
In order to support different deployment configurations, we should have different modes for the sidetree node. For example:

Mode | Comments
------------ | -------------
resolver | Node is going to handle the resolution requests
observer | Node is going to observe the blockchain data
writer | Node is going to accept the 'write' operation requests (create, update) from the clients
batchwriter | Node is going to batch up the write operations and anchor them to the blockchain

One node can operate in multiple modes and they can be then passed via config as:

````
mode: [resolver, writer]
````

**Comment by csuwildcat** [comment]
I don't understand the writer vs batchwriter distinction. What node would ever accept ops without the intention of writing a batch?

**Comment by thehenrytsai** [comment]
Done.
