### ISSUE TITLE
Replace `revoke` operation as `deactivate` operation instead

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#321]
1. Replace all referenced to `delete` in code and documentation as `revoke` going forward.
1. Disambiguate the revoked from not-found when resolving.
1. Revocation must be performed by `recover` key.
1. Revocation is the final valid operation.

**Comment by OR13** [comment]
Is this really https://w3c.github.io/did-core/#deactivate ?

I suggest that deactivated DIDs have their total information minimized, forensic analysis will return all the versions before the point of deactivation, but I still think it would be wise to set the DID Document to basically:

```
{
"@context": "...",
"id":  "did:example:123",
"deactivated": true
}
```
Is there a reason why the DID Document should retain anything that would be useful for correlation in a deactivated state? Certainly the user will not be able to do anything about it, after the fact.

**Comment by peacekeeper** [comment]
There's an older issue about this in the DID resolution spec repo.. After a DID has been deactivated, and you resolve it, do you get back a DID document with a special flag (as in your example), or do you get back a null value, or does the DID resolver raise an error?
See here: https://github.com/w3c-ccg/did-resolution/issues/5

**Comment by peacekeeper** [comment]
I put this on the agenda for tomorrow's DID resolution call, in case you have time: https://docs.google.com/document/d/1qYBaXQMUoB86Alquu7WBtWOxsS8SMhp1fioYKEGCabE/

**Comment by csuwildcat** [comment]
@thehenrytsai we should rename all of our Revoke refs and update the docs/spec to reflect Deactivate as the operation type. I can update the spec.

**Comment by OR13** [comment]
implemented

**Comment by OR13** [comment]
@thehenrytsai @csuwildcat I'm removing the spec v1 label, as this is implemented there.

**Comment by csuwildcat** [comment]
I believe this change is now reflected everywhere in the spec as of https://github.com/decentralized-identity/sidetree/pull/523, but eyes-on would help validate.
