### ISSUE TITLE
Revisit the BitcoinProcessor::revertDatabase(...) function refactor

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#329]
The revert logic in the bitcoin-processor seems different from the similar logic in Observer.ts::revertInvalidTransactions(...). Also, there could be a bug in the bitcoinprocessor.ts logic where there might be a loop if the firstTransaction in the DB is invalid. See this comment: https://github.com/decentralized-identity/sidetree/pull/315#discussion_r348766258

Another potential improvement with this bug could be how we keep the 'lastProcessedTransaction' variable updated. If we refactor the revertInvalidTransaction function as following two functions:
1. findFirstValidTransaction
1. revertTransactionsGreaterThan(block: number)

Then the current usage of the revertInvalidTransaction within processTransactions(...) function will change to the following. 
````
private async processTransactions (startBlock?: IBlockInfo, endBlockHeight?: number): Promise<IBlockInfo> {
  ...
  if (!startValid) {
    this.lastProcessedBlock = await this.findFirstValidTransaction();
    revertTransactionGreatherThan(this.lastProcessedBlock!height);

    startBlockHeight = this.lastProcessedBlock.height;
   }
  ...
}
````
This way we make sure that the lastProcessedBlock is updated and the worst behavior for the client is that they will get stale data (see lastProcessedBlock usage in ````getNormalizedFee```` function):

**Comment by thehenrytsai** [comment]
Implemented.
