### ISSUE TITLE
Implement requirements on generic DID parameters

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#338]
Currently it is unclear what generic DID parameters must be supported/implemented by a DID method  for it to be compliant with the DID spec. Need clarification from the working group before implementation can start.

**Comment by csuwildcat** [comment]
Given the state of this area of the spec, we should not concern ourselves with this, and support is not mandatory (currently)

**Comment by isaacJChen** [comment]
Decided.
