### ISSUE TITLE
Refactor the processTransaction function to make the startBlock and endBlock mandatory

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#342]
https://github.com/decentralized-identity/sidetree/blob/ef23273f5bdceabc6776155267432c0b0c8141a2/lib/bitcoin/BitcoinProcessor.ts#L443

The function has the optional parameters which make the starting & ending block logic a bit complicated whereas all the callers can probably just call the function with the correct starting and ending blockheights. For example, the function getStartingBlockForInitialization(...) can just return the genesis block in that case.

**Comment by sambarnes** [comment]
@mudiali This issue can be closed. You addressed it in this commit: https://github.com/decentralized-identity/sidetree/commit/e76cd0c2de0f7b756ada48d1200cb6730f2bd4e0

**Comment by tplooker** [comment]
Appears to have been addressed, closing issue.
