### ISSUE TITLE
Consider moving IPFS and Bitcoin microservice code to ION repo

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#346]

**Comment by csuwildcat** [comment]
Bitcoin could make sense, but why IPFS?

**Comment by OR13** [comment]
any chance we can get a mono repo structure for sidetree core?

I'd like to see the following structure:

### Core Logic / Protocol Functions
packages/sidetree-core (including test suite)

### Storage Adapters
- packages/sidetree-storage-ipfs
- packages/sidetree-storage-azure-blob
- packages/sidetree-storage-s3

### Ledger Adapters
- packages/sidetree-ledger-bitcoin
- packages/sidetree-ledger-ethereum

### Caching / Operation DB
- packages/sidetree-adapter-mongo
- packages/sidetree-adapter-couchdb
- packages/sidetree-adapter-cosmos

### Node Instances
- packages/sidetree-server-rest
- packages/sidetree-server-graphql

Then in ION and ELEM, we would npm install the packages we needed, and configure them in the http server instance.

For ION they would be:
- packages/sidetree-core
- packages/sidetree-storage-ipfs
- packages/sidetree-ledger-bitcoin
- packages/sidetree-adapter-mongo
- packages/sidetree-server-rest

For ELEM the would be:
- packages/sidetree-core
- packages/sidetree-storage-ipfs
- packages/sidetree-ledger-ethereum
- packages/sidetree-adapter-couchdb
- packages/sidetree-server-rest

We would need to npm publish versions of core to update ION and ELEM, unless we use git or npm link or...

we could add ELEM and ION implementations to sidetree repo...

then we would just run:

```
lerna bootstrap
lerna run test --scope sidetree-ion
lerna run test --scope sidetree-element
```

This would link the latest unpublished npm modules, and then run ION / ELEM tests, which would ensure that no breaking core changes occurred before you update ION / ELEM dependencies to new versions.

At Transmute, we're working to get better interop and code reuse with sidetree-core, but being split across repo's without the ability to link modules easily makes this much harder than simply maintaining a separate implementation. On the other hand, it might actually be better for the protocol that there are 2 complete separate implementations, in different repos... but its certainly harder for us to keep aligned.

**Comment by OR13** [comment]
@codeglobally ^

**Comment by csuwildcat** [comment]
^ @thehenrytsai  what are your thoughts on this?

**Comment by OR13** [comment]
Having 1 repo for people who want to contribute to sidetree to start or open pull requests against will make it easier for us to manage, and create a gravity well around the spec and reference implementation in typescript.

**Comment by OR13** [comment]
Just to provide a bit of context for how we could get "there" from "here"... We would start by moving sidetree-core to a package in the mono repo, called "sidetree-core"... next we would pull out the bitcoin and ipfs dependencies as modules next to sidetree core, ensure that they are building and testing properly, and then import them as modules instead of as files in sidetree core.

**Comment by OR13** [comment]
We'll tackle this later.

**Comment by OR13** [comment]
See https://github.com/transmute-industries/sidetree.js
