### ISSUE TITLE
Remove the hard-coded minimum fee in the bitcoin processor

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#347]
```BitcoinProcessor::writeTransaction(...)```

During the proof of fee integration, we found that the normalized fee being calculated in the testnet was too low and the bitcoin npm package was throwing exception that the min fee must be 554 (or something) satoshis. So we have added a hard-coded limit of 1000 satoshis as the fee for now. It seems that this shouldn't be a problem in mainnet as the fees there _should_ by greater than whatever the min value that the bitcoin package is enforcing. So this issue is opened to investigate and either adjust or remove this value.

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/commit/ea653198f284a7ed883e5e148fdb433ba0827681
