### ISSUE TITLE
refactor bitcoin and IPFS into ion

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#358]
Sidetree should be blockchain and CAS independent. We should move bitcoin and IPFS specific code into ion and expose common.

**Comment by csuwildcat** [comment]
IPFS is likely to be used across almost any implementer who applies Sidetree to a different chain, so shouldn't IPFS be an independent module from ION?

**Comment by isaacJChen** [comment]
Ideally, yes, they should all be in separate repo. I think we decided to put them together so we don't have to update 3 different repo whenever we make changes to a common module in Sidetree
