### ISSUE TITLE
Patches should be atomic (all applied or all dropped)

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#359]
Right now if an operation is invalid, we drop a single op and apply the rest instead of the whole batch. We might want to consider dropping the entire batch when one operation is invalid.

**Comment by csuwildcat** [comment]
If by 'whole batch' you mean dropping thousands of IDs' worth of ops if one ID has an invalid one, it depends. We can't drop everything in cases where the writing node won't be able to immediately detect an invalid state, like an invalid signature. We can drop everything for being invalid for other clearly apparent reasons, like over max size, invalid data structuring, etc. Basically, you can drop all ops in a batch only when the writer of the batch can be expected to catch an invalid op via basic checks and application of general filtering rules.

**Comment by isaacJChen** [comment]
Will take a look

**Comment by isaacJChen** [comment]
patches either apply all or drop all. Closing.
