### ISSUE TITLE
Race condition in BatchWriter.write()

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/sidetree#365]
There is a race condition [in BatchWriter](https://github.com/decentralized-identity/sidetree/blob/ddc0e58586147cafaf1bba4d6d216c3b67f15ac5/lib/core/versions/latest/BatchWriter.ts#L74)

If an operation is added to the operationQueue between the start of the execution of `BatchWriter.write()` and its end, then the wrong operation will be dequeued.

I created a test that shows how an attacker can take advantage of this race condition to create an invalid operationQueue: https://github.com/decentralized-identity/sidetree/compare/ddc0e58586147cafaf1bba4d6d216c3b67f15ac5...show-race-condition?expand=1
To run it:
```
git checkout show-race-condition
npm i
npm t
```

The solution to this problem is to dequeue only the operations that have been anchored.

**Comment by isaacJChen** [comment]
Hey. I took a quick look at it and it seems like the mock queue has a bug. 
The dequeue function in [mockOperationQueue](https://github.com/decentralized-identity/sidetree/blob/master/tests/mocks/MockOperationQueue.ts) seems to be wrong. I believe the [real queue](https://github.com/decentralized-identity/sidetree/blob/master/lib/core/versions/latest/MongoDbOperationQueue.ts) is doing the right thing though. I will test it and fix the mock.

**Comment by isaacJChen** [comment]
@gjgd I fixed the mock queue, let me know if you still have this issue. I don't think it's possible to have a race condition in batch writer because a queue should only look at the first n items regardless of how many are in it. From what I can tell the MongoDB queue has the right logic, and it is the mock that is broken.

**Comment by gjgd** [comment]
Yup, can confirm that it solved the issue
