### ISSUE TITLE
Update Operations blocking interoperability.

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#376]
I'm a bit worried that our current style of defining update operations is gonna really hurt us in the long run as new functionality comes out for DIDs...

Imagine that everyone decides that `authorization` is now a section that we need to support changes too.

Are we going to define `add-authorization`, `remove-authorization` schema for every new feature associated with a did document?

I'd much rather us a agree on a single JSON Schema, which we can update, and a simple size limit for update payloads, and just use vanilla JSON Patch...

You can infer a JSON Patch, so a user could simply edit their did document in a regular text editor, and we could calculate the JSON Patch from that... easiest way to update your DID ever.

Currently a user has to craft a special update payload, and can't easily change all the properties that they will need to be able to update in order to be linked data compliant.

**Comment by OR13** [comment]
If the did core spec were set in stone, and we already had great interoperability, I would not worry... But its far from solid, I worry we are not flexible enough to easily handle changes.

**Comment by csuwildcat** [comment]
JSON Patch and the procedures for merging in that more dynamic way significantly degraded operation throughput performance. The move to a static schema was dramatic, and I am hesitant to revisit this without a ton of instrumentation to be sure there are no perf regressions tied to such changes.

**Comment by OR13** [comment]
yeah, but it let users actually update their did document...

I can't update broken `@context`, `keyAgreement`, `capabilityInvocation`, etc... we lost support for what you see is what you get editing... pretty terrible trade IMO.

We implemented those changes, and now its impossible to improve the UX around letting a user update their did document...

Not to mention its the user's did document, what we are doing is preventing the user from actually controlling it.

**Comment by csuwildcat** [comment]
I must disagree that a stricter approach to property/value support, validation, and ingest designed to deliver on critical optimization requirements is preventing control of a user's DID. One could just as easily argue the protocol's strict limit on op size is the protocol 'controlling' how DIDs in the system are used - because it is, and that's the point. Having a strict schema/approach to ops doesn't mean the doc isn't interoperable, so I also disagree with the general framing of this issue.

**Comment by OR13** [comment]
We are creating a hard coupling between what the protocol supports and what a user can express in their did document... which means we will be making protocol updates basically forever...

**Comment by csuwildcat** [comment]
This now seems to be a virtual dupe of the Issue asking for new processing directives. Shall we close this and focus on enabling a custom property specific implementations can use to include/process op data in any way they choose?

**Comment by OR13** [comment]
closing in favor of https://github.com/decentralized-identity/sidetree/issues/383
