### ISSUE TITLE
Add support for patches with a singular action

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/sidetree#377]
Currently the names of the patches supported for an UPDATE operation are all plural:
- add-public-keys
- remove-public-keys
- add-service-endpoints
- remove-service-endpoints

This seems redundant with the fact that an UPDATE operation may contain several patches.

Here is an example: There is currently two ways a user can add several public keys to a did document

1. Two publicKeys in one patch
```json
{
  "type": "update",
  "didUniqueSuffix": "EiBQilmIz0H8818Cmp-38Fl1ao03yOjOh03rd9znsK2-8A",
  "patches": [
    {
      "action": "add-public-keys",
      "publicKeys": [
        {
          "id": "#key1",
          "type": "Secp256k1VerificationKey2018",
          "publicKeyHex": "0268ccc80007f82d49c2f2ee25a9dae856559330611f0a62356e59ec8cdb566e69"
        },
        {
          "id": "#key2",
          "type": "RsaVerificationKey2018",
          "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----"
        }
      ]
    }
  ],
  "updateOtp": "iDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLAa",
  "nextUpdateOtpHash": "EiDJesPq9hAIPrBiDw7PBZG8OUCG4XT5d6debxCUIVFUrg",
}
```

2. One public key in two patches
```json
{
  "type": "update",
  "didUniqueSuffix": "EiBQilmIz0H8818Cmp-38Fl1ao03yOjOh03rd9znsK2-8A",
  "patches": [
    {
      "action": "add-public-keys",
      "publicKeys": [
        {
          "id": "#key1",
          "type": "Secp256k1VerificationKey2018",
          "publicKeyHex": "0268ccc80007f82d49c2f2ee25a9dae856559330611f0a62356e59ec8cdb566e69"
        },
      ]
    },
    {
      "action": "add-public-keys",
      "publicKeys": [
        {
          "id": "#key2",
          "type": "RsaVerificationKey2018",
          "publicKeyPem": "-----BEGIN PUBLIC KEY...END PUBLIC KEY-----"
        },
      ]
    },
  ],
  "updateOtp": "iDk2RpPVuC4wNANUTn_4YXJczjzi10zLG1XE4AjkcGOLAa",
  "nextUpdateOtpHash": "EiDJesPq9hAIPrBiDw7PBZG8OUCG4XT5d6debxCUIVFUrg",
}
```

It would be nicer if we made the patch names singular in order to separate the roles of 
- the patch: perform one action on the did document
- the update payload: perform successive patches on the did document

It would also simplify this kind of logic: https://github.com/decentralized-identity/sidetree/blob/4b3d2e0b272263c5f0a57f74275724e73b6f4328/lib/core/versions/latest/Operation.ts#L159-L183

In that way, a patch would look like this:
```json
 {
      "action": "add-public-key",
      "publicKey": {
        "id": "#key1",
        "type": "Secp256k1VerificationKey2018",
        "publicKeyHex": "0268ccc80007f82d49c2f2ee25a9dae856559330611f0a62356e59ec8cdb566e69"
      },
    },
```
```json
{
  "action": "remove-public-key",
  "publicKey": "#key1"
}
```

Note that this need not be a breaking change. We can keep support for the plural patches and add support for singular patches:

- add-public-key
- remove-public-key
- add-service-endpoint
- remove-service-endpoint

**Comment by csuwildcat** [comment]
What is the case in which use of a plural/multi-member method that accepts single entries is prohibitive to the desired outcome of adding one item? This seems like an increase in surface area for no effective additional value. I would even be in favor of only recognizing one type of update per operation, so that we enforce that you must not use multiple `add-somethings` op objects. This would force people to be even more concise in their ops, and group all of the same type of addition/removal into one (saves space in the op, etc.).

**Comment by gjgd** [comment]
The plural method is not prohibitive to the desired outcome of adding one item, but it is in my opinion a violation of the [Separation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns) software design principle.

Using a singular action patch allows to separate the roles of:
- the patch where only one action is performed
- the update where several patches are applied.

How does that increases the surface area ?

**Comment by csuwildcat** [comment]
@gjgd it's another method to track, write code around, etc. I personally would like to move the other direction: forcibly eliminate entry prop/structural duplication in the ops by making ops only have one use of a given type per op, so they don't go making 3 entries for the same actual change type.

**Comment by OR13** [comment]
Related: https://github.com/decentralized-identity/sidetree/issues/376

The usability of updates would be even worse with your suggest @csuwildcat ...

Consider a user who wants to add a service, update a public key, and authorize the key for use with an agent... are they supposed to wait block time x 3 to do 3 things?...

On bitcoin I think thats 30 minutes to do 3 updates....

A user should be able to update all areas of their did document in a single operation...

**Comment by csuwildcat** [comment]
I don't think we're talking about the same thing - I'm not saying they
should have to do multiple ops to make multiple changes, I'm saying I have
no interest in adding singular add/remove patch methods within the op. You
absolutely can do multiple changes in one op, no one is arguing against
that.

**Comment by OR13** [comment]
We have to add a new protocol schema for every top level property of the did document... we currently support 2... `publicKey` and `service`...

There are a lot more, and the did spec supports the concept of adding new properties over time... every new property will be a protocol upgrade for us.

**Comment by csuwildcat** [comment]
I suggest we address this via a more liberal means of custom data inclusion via spec language that some implementations can choose to use. I think keys are rightfully abstracted as a core component of the current implementation, but we could add (as we discussed) an open custom property where any implementation specific value could be included and processed in the reducer function that handles compilation of each operation.

Can we close this to focus on the broader enablement of custom per-implementation data?

**Comment by OR13** [comment]
https://github.com/decentralized-identity/sidetree/issues/383

Closing in favor of ^
