### ISSUE TITLE
Change read to always read whole blocks

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#378]
We need this so the throughput limiter won't hold transactions indefinitely.

**Comment by OR13** [comment]
iIs this ION specific? I'd be interested to see links to the source regarding this issue.

**Comment by OR13** [comment]
Seems related to: https://github.com/decentralized-identity/sidetree/pull/375

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/375#discussion_r370876369

**Comment by isaacJChen** [comment]
Done
