### ISSUE TITLE
Make sure the txn fee paid is high enough to make it in the next block

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#396]
Orthogonal to the network-centric per-op fee that is imputed by the deterministic op fee rules, we must ensure that we pay enough in txn fees to make it into the next block. When creating/resubmitting a txn, make sure that we pay the per-op fee required or the minimum next block inclusion fee, whichever is greater.

**Comment by kdenhartog** [comment]
Is the intent of this issue to change it so the code sets the price dynamically rather than through the config?

**Comment by csuwildcat** [comment]
> Is the intent of this issue to change it so the code sets the price dynamically rather than through the config?

This is not exactly the same as the config values, which are more about how much cushion to add and other op-fee related bits. This is simply about making sure that we are paying enough to get into blocks, which changes from block to block sometimes.

**Comment by kdenhartog** [comment]
Gotcha. Thanks for the clarification. I'll keep an eye on the PRs related to this issue so I can learn more about how txn fees are being handled.

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/408

PR addressing the issue.
