### ISSUE TITLE
Consider tsdx for mono repo modules

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#413]
https://github.com/jaredpalmer/tsdx

Each module need not follow the exact same toolchain, although it would be nice to work towards one over time.

**Comment by JaceHensley** [comment]
We use this at Bloom for our various TS libraries and it works like a charm. The one thing I have ran into has been mixing es6 and es5 classes is kinda tricky, but it depends on the target (node or browser)

**Comment by OR13** [comment]
closing, stale, no comments.
