### ISSUE TITLE
combine ipfs, bitcoin, and core error into a common error class

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#417]

**Comment by OR13** [comment]
I assume you mean something like "SidetreeCoreError" with something like https://www.npmjs.com/package/serialize-error

?

**Comment by sambarnes** [comment]
@isaacJChen took a first pass at the issue in the above PR. Just a bunch of renaming and updating import paths. Let me know if you think more functionality needs added (like the `serialize-error` package Orie mentioned?) or if I was off base.
