### ISSUE TITLE
Investigate and optimize ipfs download to not happen at all if file size is too big

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#418]
Currently, we stop downloading IPFS file if the content size is too big. IPFS provides api that allows us to check the size before downloading, but someone can lie about it and either force us to download regardless, or deny certain files being downloaded. 

The task here is to investigate to see if there is another way to get file size accurately before downloading, and prevent the download from starting if size is too big.

**Comment by tplooker** [comment]
Current consensus is there is no way to determine the actual file size prior to download, therefore closing.
