### ISSUE TITLE
CBOR Integer Mapping Table

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#438]
We need a way to map DID Core Registry terms to integers, so that the protocol can handle changes in the external representation without breaking the protocol.

| Integer  | String |
| ------------- | ------------- |
| 10  | assertionMethod  |
| 20  | recoveryKey  |

**Comment by isaacJChen** [comment]
CBOR is a standard way to d o binary encoding of json

**Comment by OR13** [comment]
I'd rather just use https://github.com/w3c/json-ld-cbor
