### ISSUE TITLE
Revisit, finalize, and implement logging strategy

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#440]
Currently there are two camps for the logging strategy:
1. Use a dedicated logger.
1. Use console logging with support for hooks to pick up the logs as needed.

**Comment by OR13** [comment]
I think I prefer a dedicated logger, but not strongly.

**Comment by tplooker** [comment]
Element uses a custom logger implementation @gjgd will link a reference

**Comment by gjgd** [comment]
This is what we are doing for element: https://github.com/decentralized-identity/element/blob/405488e92867c318b1fe40c3af3b8d7a64dea99e/packages/element-lib/src/sidetree/logger.js

**Comment by thehenrytsai** [comment]
Implemented.
