### ISSUE TITLE
Remove/deactivate service endpoint support 

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#455]
The current support for service endpoint is limited. Need to clean it up before mainnet.

**Comment by csuwildcat** [comment]
We may even be able to cut it for this release

**Comment by csuwildcat** [comment]
I don't want to completely remove the concept of this from the code, given there are some rather straightforward service endpoint types I would like to make available as quickly as we can after this mainnet freeze/stabilization phase.
