### ISSUE TITLE
Perform validation against each operation data in batch file at observing time

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#459]
After the file restructuring, per op validation was done in anchor file, but it is not done in batch file.

**Comment by thehenrytsai** [comment]
After offline discussion, this might end up being the desired behavior to maximize the throughput of the `Observer`. We will need to measure the performance hit of introducing this check to the `Observer` before deciding to implement this.

**Comment by tplooker** [comment]
No longer actionable, we are doing this at resolution time now instead of observing time.
