### ISSUE TITLE
Enable runtime configuration of what the sidetree is persisting

### ISSUE THREAD

**Issue by ebaizel** [decentralized-identity/sidetree#47]
There has been some discussion around extending the sidetree model to allow for storing more than DIDs.  Example, storing attestations / claims.

The underlying requirements of batching transactions and persisting an anchor hash would be the same, but the processing of each item would be unique, eg for DIDs we'd need to validate the change, whereas for an attestation it'd probably be more of a straightforward save.

As far as implementation, this could be a run time config that swaps in the appropriate module based on what it is being instantiated for.

**Comment by csuwildcat** [comment]
I'd say the only initial, imperative bit here is to make sure that we don't hard-bind the core internals to DID Documents. As long as we can abstract enough of the target payload out from the other aspects of the system, we should be able to allow for such alternative uses.

**Comment by isaacJChen** [comment]
Pending document composer plug-in feature.
