### ISSUE TITLE
spec: shouldn't constrain key type in spec body

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#496]
https://identity.foundation/sidetree/docs/spec/#standard-patch-actions

Section 9. Step 3.2:

> The object MUST include a type property, and its value MUST be one of the following supported key types:
> Secp256k1VerificationKey2018

The key type supported by a particular DID Method is a spec "parameter". The spec body shouldn't constrain this selection.

Perhaps the supported key type should be added to the table: https://identity.foundation/sidetree/docs/spec/#protocol-versioning-default-parameters

**Comment by csuwildcat** [comment]
I could change the language to say something like: "The object MUST include a type property, and its value MUST be one of the key types that the implementation supports". The point of this particular Patch Action is to possibly constrain the types, so I think the middle ground is the bake in the concept of an allowed key type list, and let the implementation specify what that is. Reminder: this Patch Action is only a MAY implement, so it's not something folks have to use.

**Comment by troyronda** [comment]
> I could change the language to say something like: "The object MUST include a type property, and its value MUST be one of the key types that the implementation supports". 

Makes sense.

**Comment by csuwildcat** [comment]
I believe I fixed this in https://github.com/decentralized-identity/sidetree/pull/523. Take a look to see if the new language good, then we can close this out.
