### ISSUE TITLE
spec: operations singular or plural

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#504]
https://identity.foundation/sidetree/docs/spec/#batch-files

The example has `"operations"`, while step 1 of the text is:
The Batch File MUST include an **operation** property, and its value MUST be an array.

**Comment by troyronda** [comment]
Additionally:
Each **operation** entry to be included in the Batch File MUST be a base64 encoded value of the operation data matching the type of operation it represents, and shall be appended to the **operation** array as follows

The operation link above should also point to https://identity.foundation/sidetree/docs/spec/#did-operations rather than https://identity.foundation/sidetree/docs/spec/#did-operation

**Comment by troyronda** [comment]
Additionally these links seem to be broken:
- Recovery Operation Data Objects
- Anchor File Recovery Entry
- Map File Update Entry
- operation entry (mentioned in previous comment).

**Comment by csuwildcat** [comment]
Fixed in https://github.com/decentralized-identity/sidetree/pull/524, when it is merged.
