### ISSUE TITLE
Switch to JWS Compact format for signed data in operations

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#515]
To better align with the more commonly used compact format (which almost all JWT implementations use), change from the flattened JSON format to the compact format for JWS representations in the operations sections of our CAS files.

**Comment by OR13** [comment]
We need examples for all DID Operations, in compact JWS form.

This is a missing link between the HTTP API Spec and the Core Spec.

**Comment by OR13** [comment]
We need to update the core spec and swagger... https://identity.foundation/sidetree/docs/swagger/

with the exact compact JWS that is submitted.
