### ISSUE TITLE
Rename `publicKeyJwk` to just `jwk` per patch spec.

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#539]

**Comment by OR13** [comment]
https://w3c.github.io/did-core/#dfn-publickey

Why?

**Comment by OR13** [comment]
Who made the decision to create this issue, and why is this a high priority?

**Comment by thehenrytsai** [comment]
I am implementing this to meet the Sidetree Core spec, will let Daniel comment. Anything that is not meeting the spec is marked as high priority.

**Comment by OR13** [comment]
Specifically you are implementing reference implementation support for: https://identity.foundation/sidetree/docs/spec/#add-public-keys

**Comment by OR13** [comment]
it appears this is for the "internal did document representation and is not expressed externally... as long as that remains true, it's fine.

**Comment by thehenrytsai** [comment]
You are right, not expressed externally.

**Comment by thehenrytsai** [comment]
Implemented.
