### ISSUE TITLE
Note on JSON canonicalization in spec

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#564]
In DID Suffix Composition section.

> Once assembled, `Base64URL` encode the JSON object.

It would be helpful to note in the spec that JSON Canonicalization MAY be performed prior to the BASE64URL encoding of the JSON Object. It would also be helpful to reference [JSON Canonicalization Scheme](https://tools.ietf.org/id/draft-rundgren-json-canonicalization-scheme).

**Comment by csuwildcat** [comment]
Np, will add today

**Comment by troyronda** [comment]
Was added here: https://github.com/decentralized-identity/sidetree/pull/577/files#diff-89b45be55b20134736ee477b94a59746R45
