### ISSUE TITLE
Draft at https://identity.foundation/sidetree/docs/spec should link to latest

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/sidetree#575]
The draft at https://identity.foundation/sidetree/docs/spec/#create is out of date compared with `master`, and I'm not sure where/how to view the current content on the web. Given how quickly the spec is evolving, it'd be really helpful to have an evergreen github pages hosted copy of the current master branch, and to link to it from the top of https://identity.foundation/sidetree/docs/spec so that folks exploring the spec have no trouble finding the latest work.

**Comment by csuwildcat** [comment]
That was the old URL, the spec was moved to https://identity.foundation/sidetree/spec/, and GitHub has a zombie copy still alive on GH Pages at that old path.

**Comment by troyronda** [comment]
The GitHub repo description also has the old URL.

**Comment by jmandel** [comment]
it would very much be worth cleaning up these references. I spent way too much time looking at stale content and being very confused about the gaps in my implementation :-)

**Comment by csuwildcat** [comment]
Looks like GH-Pages branch still has the old file sitting there. For some reason it didn't delete it a long time ago. I will either delete the page manually or redirect the page with an HTML metatag to the new destination.

**Comment by csuwildcat** [comment]
We have now corrected the repo/spec so the correct, up-to-date spec can be found at a single URL: https://identity.foundation/sidetree/spec/
