### ISSUE TITLE
Move API sections of the core protocol spec to a separate spec document

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#578]
@troyronda I believe we agreed that the API would be done as a separate specification document, so we could version it independently of the core protocol. This is due to the fact that the two will likely diverge, thus shouldn't be coupled under the same path version of the core spec.

**Comment by OR13** [comment]
@csuwildcat to setup the document and URLs

**Comment by csuwildcat** [comment]
This is done and published.
