### ISSUE TITLE
Section 11.1 Multikey support for 11.1 operations

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#587]
Have we considered how we might define multisig support for operations that update the did document.   

How do we keep it simple while also making it easy to build around the organizations structure?

**Comment by OR13** [comment]
Needs a multisig suite for reference.

**Comment by kdenhartog** [comment]
If we add BLS key support as a JWK and define a JWS suite for BLS signatures (for aggregate/threshold signature support) then we can get this feature. That's likely the easiest way to handle this in a non-repudiable manor.

Alternatively, we can use Shamir's secret sharing with supported crypto today and manage this at the application layer rather than making it a concern here.

Each method has their tradeoffs, but at the very least this can be done today using SSS if needed until other methods are defined.

**Comment by kdenhartog** [comment]
Closing this issue - I don't forsee a need for this at this point and the most practical way someone would approach this these days would be by making a feature request to support the https://github.com/w3c-ccg/verifiable-conditions/ VM suite
