### ISSUE TITLE
Section 11.1.1 Leniancy around requiring PublicKeyJWK

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#588]
We want to be able to use BLS keys here soon and the process to get them registered is painful

Looking for an interim solution that won’t be in violation of the spec

Secp256k1 is currently in violation of the spec because it’s not registered as well.

Remove section 16.3 because of this text?

**Comment by troyronda** [comment]
A few thoughts:
- "ops" keys vs public keys emitted into the DID Documents (e.g., auth, assertion) should have different considerations & restrictions.
- A particular implementation should set its supported list.
- Even for `Ed25519VerificationKey2018`, which doesn't support `publicKeyJwk`, the input can still be a `jwk` in add-public-key and can be transformed to publicKeyBase58 in the output DID document.

**Comment by OR13** [comment]
@kdenhartog Can you add an example of adding publicKeyBase58 keys to a did document to the spec.

**Comment by csuwildcat** [comment]
Per discussion with @kdenhartog, we have a proposal to stick to JWK representations, but make it more clear that we are not blocking out unregistered JWK formatted key representations from being added. Currently the reference implementation will still require `secp256k1` keys for ops-capable keys, but that is something we all plan to address later as we add support for other key types (e.g. ED25519)

**Comment by kdenhartog** [comment]
spec for this is to be written still, but intent is to get it done when I get the time.

**Comment by OR13** [comment]
@kdenhartog to define JWK format for BLS.

**Comment by OR13** [comment]
@kdenhartog removing spec v1 label from this, its not urgent.

**Comment by kdenhartog** [comment]
We just going to handle as an extension then?

**Comment by OR13** [comment]
There is no need for normative spec v1 language on this issue. IMO, this is more of an issue for did-core-registries, but this is still your issue please work to close it out however you think is best.

DID Core > DID Core Registries > Sidetree > Sidetree Methods

sidetree requires JWK / JWS for operations.

**Comment by kdenhartog** [comment]
Yeah, I've dropped the plate on getting this done ASAP. Will find a solution and get back to as soon as I can. The reason I marked it as SpecV1 was because we discussed on a previous call that we'd state support for BLS keys in sidetree because it's not IANA registered.

**Comment by tplooker** [comment]
I have discussed this with @mikelodder7 we are intending on drafting the BLS12-381 JWK key representations as the following

A BLS12-381 public key in G1

```
{
    "kty": "EC",
    "crv": "BLS12-381_G1",
    "x": "<base64 encoded bytes>"
}
```

Where the length of x is 384bit base64url encoding of the octet string representation of the coordinate

A BLS12-381 public key in G2

```
{
    "kty": "EC",
    "crv": "BLS12-381_G2",
    "x": "5EiLZm2APO4AUy6oqRB-B5jmQr9RcWx_EclKX0s3RGE"
}
```

Where the length of x is 768bit made up of the concatenation of two 384 bit x co-ordinates known as x_a and x_b in the following form (x_a || x_b) as a base64url encoding of the octet string representation of the two coordinates.

**Comment by OR13** [comment]
@tplooker awesome... i suggest you implement bi-direction conversion for base58 and hex as convenience in your key library.

You should also cross link this issue with the repo that holds your key implementation, and the repo that holds your spec for JWK... this issue is for tracking support of JWK in sidetree.... and based on the current conversation, it sounds like there will be no action for this issue, especially if we can use `JsonWebKey2020` to represent BLS Keys.

**Comment by tplooker** [comment]
We already have base58 support in [this](https://github.com/mattrglobal/bls12381-key-pair) library and are intending on adding in jwk support too, can you explain why we need hex?

**Comment by OR13** [comment]
nobody needs 'hex'... its convenient, given that many people prefer it to base58btc... which is a pseudo standard for serializing binary by comparison.... for example, it's incredibly common in IoT / embedded systems to use hex.

**Comment by csuwildcat** [comment]
Is there an action item for spec text here, or are we good?

**Comment by OR13** [comment]
I suppose the only action item would be test vectors to demonstrate support for key types other than JWK...  assume that if there is no test, the feature does not actually work, which is a nice way of saying that sidetree did methods only support JWK based verification methods.

**Comment by OR13** [comment]
I'm personally not bothered by sidetree only supporting JWK... and it will certainly ensure that JWK continues to be relevant as it ages, since new crypto will need to be registered with IANA in order to be used by sidetree

**Comment by kdenhartog** [comment]
Section 12.1.1 should cover it now. The language states "he object MUST include a publicKeyJwk property, and its value MUST be a public key expressed as a IETF RFC 7517 compliant JWK representation for a KEY_ALGORITHM supported by the implementation." Which could be interpreted to mean as long as it's a JWK format and it's supported in the implementation then it's fine. Given there's no normative statements regarding registration in IANA it's fine. I think this one is fine to close now.

**Comment by OR13** [comment]
Our did key implementation produces `did+json` for a number of key types... which can in turn be used to add these keys to sidetree because they all use publicKeyJwk.

https://did.key.transmute.industries/

I agree this can be closed.

If sidetree  methods wanted to transform keys like we do in did key, they could.
