### ISSUE TITLE
Namespace authority

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#590]
naming of the uri’s (e.g. ion vs elem vs etc). We lack any sort of description around how methods should be named. This will be important as we have competing interests such as multiple sidetree methods running on ethereum. Not encouraging this, but understanding this is a necessary countermeasure.

How does this assist with the forking problem?

**Comment by csuwildcat** [comment]
Can you clarify a bit about what you are thinking, and how you would approach either language or some mechanism to do this?

**Comment by kdenhartog** [comment]
Right now, we implicitly build the naming of the method using `did:methodName:network:....` If we want to continue with this path we should make it explicit. Maybe, we want to go the route of `did:sidetree:ion:test`. In any case I think we should be making recommendations around how the front part of the did gets decided and may want to make a note about how it's used to handle forks. For example, maybe the way we indicate a fork is instead of using "main" we use last 5 characters of the first block of a fork prepended to the block number. Handling forking I think can be noted and not defined in specv1, but we should at the least note it.

This isn't anything that's going to be difficult to define, but we should put a bit of thought in it ahead of time I would think.

**Comment by OR13** [comment]
@kdenhartog can you add a "note" about forking... ETH / ETC...

**Comment by kdenhartog** [comment]
Pending close once PR is merged.

**Comment by OR13** [comment]
This was merged, closing.
