### ISSUE TITLE
Section 12.2 Add note about “minimal confirmation”

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#591]
E.g. are we implying 6 blocks on BTC here?

Do we encounter a race condition if nodes take a different strategy here. E.g. one propogates at 6 blocks, while one propogates at 0.

Could we solidify a method of ordering logic in section 12.3 to avoid this. E.g. hash of transaction # + time and smallest hash wins

**Comment by kdenhartog** [comment]
@csuwildcat when you get a chance can you add the comment in here about what you mentioned on the call today about mempools and commitments and how it could be an attack so I can formalize it as a warning in the spec and close this issue?

**Comment by csuwildcat** [comment]
Done and pushed: https://identity.foundation/sidetree/spec/#cas-propagation-delay
