### ISSUE TITLE
Advantages and disadvantages of making the DID Suffix the initial recovery commitment

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#592]
Disadvantage: may break the initial-values self-certification property. Check what’s needed for that first.

Advantage: Makes IDs of the keys easier to handle when being done in a KMS. E.g. in Azure Key Vault I can name the key did:sidetree:123#key1 rather than a UUID.

**Comment by csuwildcat** [comment]
Is there an outcome from the above that we're seeking? I don't think we should change this at this point, fwiw.

**Comment by kdenhartog** [comment]
I'm not remembering what I wanted this for based on my previous comments. I'm fine with closing this for now and we could re-open it if others found it to be a useful feature they need in the future.
