### ISSUE TITLE
Section 11.1.1: Support for additional key usages

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#593]
Should we make this compatible to easily add support for additional usages that are registered as extensions?

**Comment by csuwildcat** [comment]
My preference is that for folks who use the `add-public-keys` Patch Action, we extend this by registering new `usage` values in the `add-public-keys` section, with the directives about where in the DID Document they are to appear (as well as any other requirements/logic that may need to happen to do it). If that is ok, then I would be fine taking in any that we want to define, but would ask that we do so post-Spec v1, given the push to finish out this revision. Let me know what you all think.

**Comment by kdenhartog** [comment]
Yeah, I agree that this would make sense post-specv1. Right now we don't have much of a reason for additional ones and they would need to be registered within the did-core-registries unless they're being used to produce a JSON-LD specific did document that will be consumed by only JSON-LD consumers.

In this case, I suspect we'll want broader compatibility than that so we'll want to rely upon registries to make this possible.

**Comment by OR13** [comment]
We should add the following verifiactionMethods to the sidetree context:

"operations", "recovery"...

for DID Methods that don't use the "internal data model", they an use these sections with JSON patch alone.

**Comment by OR13** [comment]
These are in the current JSON-LD context... if they spec tool would render things properly we could see the changes.

**Comment by OR13** [comment]
Its defined here: https://github.com/decentralized-identity/sidetree/blob/master/spec/markdown/json-web-signatures.md#verifying

**Comment by OR13** [comment]
@kdenhartog @csuwildcat As the spec is written today, a key usage can be handled as it is in did core, via `authentication` and `assertionMethod` or how it is internally in the implementation in this repo / using the internal data model / JSON Schemas.

I suggest we close this issue, if you want additional usages, you have a did core compliant way of doing it with JSON Patch, and a Microsoft way of doing it with internal data model.

**Comment by kdenhartog** [comment]
When I opened this issue my understanding was that we'd define new proof purpose formats for things like DIDComm. However, based on [did-core/#268](https://github.com/w3c/did-core/issues/268) I'm thinking we're not going to have nearly as many of these proof purposes to define.

**Comment by OR13** [comment]
We added support for everything needed to issuer VCs, use DIDComm and work with encrypted data vaults.

https://github.com/transmute-industries/sidetree.js/blob/master/packages/core/src/DocumentComposer.ts#L60

**Comment by kdenhartog** [comment]
That looks good to me. I'd be good to call this one done.
