### ISSUE TITLE
Section 11.1.1: Support for keys by reference

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#594]
Should it be possible to add a key by reference rather than by value? E.g. the raw public key bytes can live in a different did document

**Comment by OR13** [comment]
First Key: https://ipfs.io/ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTQ

Second Key: https://ipfs.io/ipfs/QmW2WQi7j6c7UgJTarActp7tDNikE4B2qXtFCfLPdsgaTM

how long will you try and resolve a key by URI before considering it to be an attack?

**Comment by kdenhartog** [comment]
Depends on the implementation I suppose. This is currently accepted through JSON-LD and is described within the DID spec. I don't think the resolver necessarily needs to handle the depth, but it should expect that a reference to another did-url is ok.

**Comment by csuwildcat** [comment]
What is the action here? Are we expecting Sidetree Methods to do something specific about this?

**Comment by kdenhartog** [comment]
I think some of the input validation logic needs to be supported and may want to make mention of redirect constraints as a should for resolution logic.

**Comment by kdenhartog** [comment]
See this PR for additional considerations here: https://github.com/w3c/did-core/issues/301

**Comment by kdenhartog** [comment]
I don't believe we practically need this feature in did documents at this point. I'm good with closing this feature request for now and if someone else has a practical need for this in the future they can open a new issue for it. Closing with no action
