### ISSUE TITLE
Update resolution endpoint in REST API and swagger

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#605]
Change to `/sidetree/<ver>/identifiers`

Note: `sidetree` is intended to be replaced by the DID method name. E.g., `/foo-method/0.0.1/identifiers`.

**Comment by OR13** [comment]
this is a little confusing:

`/elem/0.0.1/identifiers/did:elem:ropsten:EiBJJ...`

does the version apply to the did method? or the sidetree api?

this would be better:

`https://example.com/sidetree/v1/dids/did:elem:ropsten:EiBJJP...`

maybe we change the endpoint name in v2....

`https://example.com/sidetree/v2/identifiers/did:elem:ropsten:EiBJ...`

Maybe we add support for trustbloc later...

`https://example.com/trustbloc/sidetree/v2/identifiers/did:trustbloc:EiB...`
`https://example.com/elem/sidetree/v1/identifiers/did:elem:ropsten:EiBJ...`
