### ISSUE TITLE
JwsVerificationKey2020 not in the contexts

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#612]
The contexts listed in https://identity.foundation/sidetree/spec/#context do not contain `JwsVerificationKey2020`

**Comment by troyronda** [comment]
@OR13

**Comment by troyronda** [comment]
- https://www.w3.org/ns/did/v1
- https://identity.foundation/sidetree/context-v1.jsonld

**Comment by troyronda** [comment]
@OR13 should `JwsVerificationKey2020` be defined in https://identity.foundation/sidetree/context-v1.jsonld ?

**Comment by OR13** [comment]
yes, we should define them.

**Comment by OR13** [comment]
@kdenhartog can you open pull request on the CCG and DID core registries to address this, so we can register this correctly once.
