### ISSUE TITLE
Should REST APIs follow a consistent style guide?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#613]
As was mentioned in PR #596 we discussed having the path use kebab-case and the query strings use snake_case. Is there a styling guide that we should reference to keep this consistent for the REST APIs?

@OR13 here's the issue. Please reapply issues if you don't think I tagged correctly. I wasn't sure if this should be defined before v1, but opted it in because it's small.

**Comment by troyronda** [comment]
@kdenhartog Please see https://github.com/decentralized-identity/sidetree/issues/624 and https://github.com/decentralized-identity/sidetree/pull/627

**Comment by kdenhartog** [comment]
Cool looks good, this can be closed. Thanks @troyronda
