### ISSUE TITLE
Reference implementation contains replace action

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#622]
The reference implementation contains the `replace` action.

https://github.com/decentralized-identity/sidetree/blob/a13d2326bc851ce906ffdea5df70a384fef70ad2/lib/core/versions/latest/DocumentComposer.ts#L384

This action is not part of the [current spec](https://identity.foundation/sidetree/spec/#did-state-patches), but is referenced in the code (and some tests).

**Comment by troyronda** [comment]
As a side-effect, this action also exposes internal data structures:
- publicKeys
- serviceEndpoints

that other implementations MAY model differently. This makes it difficult to exercise the same tests across implementations (and will also affect potential interop for the basic model).

**Comment by csuwildcat** [comment]
I don't think this replace action is actually used anywhere anymore - it may be a vestigial thing that just wasn't removed from code. I'll let @thehenrytsai comment further.

**Comment by csuwildcat** [comment]
@thehenrytsai please comment on this so we know if we can close it or not - I do not believe this is in the codebase any longer, right?

**Comment by thehenrytsai** [comment]
It is coded and used, was not aware that replace is taken out of the spec?

**Comment by csuwildcat** [comment]
@thehenrytsai I was not aware of any such Patch Action, at least not something exposed for public operation delta use. Are you saying there's some Patch Action that should be documented simply called `replace` that does something different than the ones specified in the spec? Or are you saying there's some sort of internal code that uses a purely non-standard method to do something that has no outward surface for implementers/users of the spec?

**Comment by OR13** [comment]
Decision to delete "replace".

It will not be documented in the spec.

Not supported in the reference implementation.

**Comment by thehenrytsai** [comment]
Assigning to Daniel to close.

**Comment by csuwildcat** [comment]
Closing with spec/implementation updated to match resolution
