### ISSUE TITLE
REST API query parameters with dash 

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#624]
There is a proposal to use dashes for query parameters (in addition to path segments).
https://github.com/decentralized-identity/sidetree/pull/596#issuecomment-620665390

@OR13 @kdenhartog @csuwildcat @thehenrytsai

**Comment by OR13** [comment]
Please provide examples in the issue to kick off discussion.

**Comment by csuwildcat** [comment]
Example: I believe path segments/url parameters now appear as underscores, and should be dashed, as that is the common form for segments and url params on the web.

**Comment by troyronda** [comment]
Example from the [Swagger API](https://identity.foundation/sidetree/docs/swagger/#/Content%20Addressed%20Storage/readContent):

Current definition in Swagger docs (`max_size` query parameter):
`GET /sidetree/0.0.1/cas/13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de?max-size=200`

Proposed (`max-size` query parameter):
`GET /sidetree/0.0.1/cas/13550350a8681c84c861aac2e5b440161c2b33a3e4f302ac680ca5b686de48de?max-size=200`

**Comment by OR13** [comment]
@csuwildcat 

A. `/sidetree-transations?sidetree-operations=1`
B. `/sidetree_transactions?sidetree_operations=1`
C. `/sidetree-transations?sidetree_operations=1`
D. `/sidetree_transations?sidetree-operations=1`

**Comment by OR13** [comment]
query params should be snake case, path segments should be kebabe case...

query params are converted to objects commonly.

**Comment by OR13** [comment]
Example: https://restfulapi.net/resource-naming/

**Comment by OR13** [comment]
I wouldn't be opposed to A or C. I'm opposed to B and D.

**Comment by csuwildcat** [comment]
My preference is A, given it is the dominant way URL segments and params are represented on the Web. This was basically universally adopted after recognition that Google and other web crawlers indexed paths assuming dashed items (dog-and-cat-supplies) could be matched as either one token or separate tokens, whereas underscored (dog_and_cat_supplies) would only match the exact sequence/token as a whole.

**Comment by troyronda** [comment]
I think concretely the swagger changes are:

- path (was missed on previous edit)
  - `/blockchain/transactions/firstValid` => `/blockchain/transactions/first-valid`
- query parameters
  - `max_time` => `max-time`
  - `transaction_time_hash` => `transaction-time-hash`

**Comment by kdenhartog** [comment]
Yeah my preference is A as well, but could live with C.
