### ISSUE TITLE
capability key usages

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#626]
Comparing the Sidetree protocol spec to:

- [did:elem example document ](https://uniresolver.io/1.0/identifiers/did:elem:EiAS3mqC4OLMKOwcz3ItIL7XfWduPT7q3Fa4vHgiCfSG2A)
- [did:key spec](https://w3c-ccg.github.io/did-method-key/)

Sidetree protocol [add-public-key](https://identity.foundation/sidetree/spec/#add-public-keys) doesn't currently have definitions for the capability usages.
- capabilityDelegation
- capabilityInvocation

From the [DID Core Spec](https://www.w3.org/TR/did-core/):

> A public key is just one type of verification method. A DID document expresses the relationship between the DID subject and a verification method using a verification relationship. Examples of verification relationships include: authentication, capabilityInvocation, capabilityDelegation, keyAgreement, and assertionMethod.

**Comment by troyronda** [comment]
@csuwildcat in the current conventions, would the usage be named:

- `delegation` and `invocation`; or
- `capability_delegation` and `capability_invocation`; or
- other?

**Comment by csuwildcat** [comment]
It's troubling to me that the spec includes a bunch of 'verification methods' the concept of which isn't well-specified, with many verification methods like these which literally aren't specified in any way at all. They might as well read "DerpabilityBinvocation" and it would have the same meaning and effect for use. I am not sure I would block these additions, but it's unclear what they even do vs some other random strings that do other random things.

**Comment by OR13** [comment]
or we can just stop using a "internal data model"... transmute will support these with ietf-json patch alone.

**Comment by csuwildcat** [comment]
It's not about an internal data model, and you will inevitably have a concept of an internal transitional state to migrate users from one version of DID Document supported features if any are changed, renamed, relocated, etc.

**Comment by csuwildcat** [comment]
I think it's fine to add these, @troyronda, just sucks that they're essentially random strings in the DID spec we're adding simply because they exist in a note with no definition.

**Comment by OR13** [comment]
@csuwildcat feel free to contribute to did core registries and define how they are already used for Authorization Capabilities for HTTP Signatures here:

https://github.com/digitalbazaar/http-signature-zcap-invoke
https://github.com/digitalbazaar/http-signature-zcap-verify

Transmute, Digital Bazaar and Secure all use these with different did methods today...

I've already got a fairly large amount of changes pending here: https://github.com/w3c/did-core-registries/pull/42 or I would....

**Comment by OR13** [comment]
This is required for interop, and has been merged.
