### ISSUE TITLE
Should not treat all situations when anchor file does not point to a map file as invalid

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#631]
This is a legitimate case when all operation are deactivates, there would be no map and chunk files. Current code assumes map file must exists, thus invalidates the batch when this occurs.

**Comment by csuwildcat** [comment]
Great catch!

**Comment by OR13** [comment]
Can we add a note the spec about this.

**Comment by OR13** [comment]
@csuwildcat spec needs normative language about making this behavior valid.

**Comment by thehenrytsai** [comment]
Fixed.
