### ISSUE TITLE
Bugs in operation keys info in `methodMetadata`

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#638]
Bugs in operation keys info in `methodMetadata`, some are debatable:
1. Should not have `controller` property.
1. Recovery key is called `recoverKey`, operation keys should probably be called `operationKeys` for consistency.
1. Might want to considering renaming `publicKeyJwk`.

**Comment by csuwildcat** [comment]
Remove operation keys from `methodMetadata`
