### ISSUE TITLE
Stabilize Context Versioning

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#641]
Proposed Stable JSON-LD Context:

https://identity.foundation/sidetree/contexts/sidetree-v0.0.0.jsonld

**Comment by csuwildcat** [comment]
Another option might be something like this, if we're trying to disambiguate between what it is a context about: https://identity.foundation/sidetree/contexts/doc-v0.1.0.jsonld

**Comment by OR13** [comment]
done, closing
