### ISSUE TITLE
Ensure resolution processing accounts for true operation order regardless of ledger time order

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#654]
Operations should be processed based on their deterministic, owner-intended order from one to another, regardless of the exact order of their anchoring transactions. Operation ordering should transcend ledger time ordering, with ledger time ordering being used as a 'tie breaker' if there are two valid ops that deterministic ancestors of a previous operation. In a case where two operations share the same ancestor, the earliest in ledger time order shall be deemed valid. There are two options for v1 of the spec:

1. Use what is available within operations today to accomplish this by iterating all operations and processing them in the linked order their commit/reveal values naturally form, using earliest ledger time to resolve any conflicts (as noted above).

2. Add a version number to operations that makes the order explicit and enables more performant processing. In a version number scheme, you would want two numbers that separate Recovery/Checkpoint ops from Update ops. This would be a new value in the Anchor/Map File entries of each operation - for example: `{ op_number: 1.2, ... }`, wherein the `1` means that it is the first recovery in recovery ordering, and the `2` means the operation is the second update after the first recovery. During resolution you would sort by this number, then sort by ledger time order, resulting in the earliest numbers first, then ordered by earliest appearance in the ledger. This would provide an efficient basis for iterating operations during resolution.

My preference is Option 2, but we could do Option 1 if we didn't want to add an explicit mechanism and specification text that directs its use.

**Comment by OR13** [comment]
+1 to option 1, thanks for the clear description of the problem.

**Comment by csuwildcat** [comment]
@OR13 I screwed up and transposed my preference, so if you think Option 1, maybe we should chat?

**Comment by csuwildcat** [comment]
Pros of Option 1: it requires very little spec change, and technically we can make sure to do this today (so, for example, ops aren't needlessly dropped if transactions land out of the expected order) using the values in the system we already have. Cons: it doesn't allow for straightforward sorting and order processing, which will be far less performant.

Pros of Option 2: it would allow fast sorting of ops and you could process them quickly in one pass, without retracing a bunch. It also could unlock the ability to migrate ledgers more easily (if that was ever necessary)

**Comment by OR13** [comment]
If you don't need it for security reasons, it shouldn't be added.

Can you walk me through how I would abuse this as an attacker who had discovered a commit / reveal value?... pretty sure I can force a bunch of garbage operations to be stored...

I think there are a bunch not fully documented security considerations with option 2.

**Comment by csuwildcat** [comment]
After a chat with @thehenrytsai and @isaacJChen, Option 2 does not deliver any real benefits over the simpler Option 1, so we can go with Option 1 and simply adjust the resolution portion of the spec to reflect this condition.

**Comment by OR13** [comment]
Pending review of https://github.com/decentralized-identity/sidetree/pull/674

**Comment by thehenrytsai** [comment]
Done.
