### ISSUE TITLE
ValueTimeLockVerifier::calculateMaxNumberOfOperationsAllowed should use the `normalizedFeeToPerOperationFeeMultiplier` from the block when the lock was written

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#655]
The `calculateMaxNumberOfOperationsAllowed ` uses the `normalizedFeeToPerOperationFeeMultiplier` from the block when the operations were written. We should be using the `normalizedFeeToPerOperationFeeMultiplier` protocol value from the block when the lock was written. So basically use the `ValueTimeLockModel.lockTransactionTime` of the parameter which was passed in.

**Comment by mudiali** [comment]
A couple of ideas to solve this:

1. Have a class within the versioned code which has very specific functions to return the protocol parameter for a given block. The function could be a dirty hack which literally just looks up in the folder structure and returns the required value.
1. Come up with a holistic solution to pass the versioned protocol parameters down to the versioned code.
1. For this specific case, we can include these parameters (required for the valuetimelock) when returning the values from the blockchain. Basically the `Blockchain::getValueTimeLock(...)` function fetches the value from the blockchain and then adds the required parameters to the structure so that it can be used during the verification process. This probably seems like most cleaner solution in this specific case.

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/741/files

done
