### ISSUE TITLE
Improve bitcoin startup and avoid DB deletion.

### ISSUE THREAD

**Issue by mudiali** [decentralized-identity/sidetree#667]
https://github.com/decentralized-identity/sidetree/blob/731dd56f7e2581d82ed730f2aa4839b802d67f3a/lib/bitcoin/BitcoinProcessor.ts#L464

Currently, `getStartingBlockForInitialization` functions checks whether the last transaction-time stored in DB hasn't forked. If not forked, it assumes that block as the starting point (the above if statement). We can improve the above if statement to read from the quantile DB to figure out what was the last group that we saved correctly and start from that point onwards. 

**Need to think through to make sure that if there was a fork after the last transaction-time stored in DB then is doing this ok?**

Pseudo-code to refactor the above if statement:

````javascript
if (lastSavedBlockIsValid) {
  const lastSavedGroup = quantileCalculator.getLastGroupId();
  const newGroupToStart = lastSavedGroup++;
  const firstBlockInNewGroupToStart = this.getFirstBlockInGroup(newGroupToStart);
  lastValidBlock = await this.trimDatabasesToFeeSamplingGroupBoundary(firstBlockInNewGroupToStart - 1); 
}
````
-------------------------------

**Possible Solution 2**
Another solution that came up with offline brainstorming, and is probably better due to catching the forking issue, is that we save either the lastProcessedBlock + hash or lastGroup.lastBlock + hash in the DB. Then at startup check the block + hash to ensure that there's no fork.

**Comment by thehenrytsai** [comment]
Implemented and checked in.
