### ISSUE TITLE
Move reveal value into signed payload

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#668]
To prevent all classes of possible op-replay attacks, move the reveal value into the signed JWS payload, and note in the spec that all commitments must be unique.

**Comment by OR13** [comment]
This is a reference implementation only issue now.

**Comment by csuwildcat** [comment]
@isaacJChen I believe this is closed out, right?

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/679
