### ISSUE TITLE
Change anchored operation count to plain number instead of encoded value

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#688]
Currently looks like this: `ECcAAA.QmWd5PH6vyRH5kMdzZRPBnf952dbR4av3Bd7B2wBqMaAcf`

Will look like this: `10000.QmWd5PH6vyRH5kMdzZRPBnf952dbR4av3Bd7B2wBqMaAcf`

**Comment by thehenrytsai** [comment]
Assigning to Daniel to update spec and close.

**Comment by csuwildcat** [comment]
Added in latest PR
