### ISSUE TITLE
Refactor code commonly used by all Sidetree microservices to lib/common

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#69]
There are code commonly used by `sidetree-core`, `sidetree-bitcoin` and `sidetree-ipfs` such as:

Response
ResposeStatus
etc

Currently code are duplicated in three places, would be nice to refactor into a common repo.

**Comment by OR13** [comment]
agree. I have a reference i can share.

**Comment by thehenrytsai** [comment]
Done in c77859bdfc023b80e6528ceb81605b25c171f6f0.
