### ISSUE TITLE
DID Document examples using sidetree?

### ISSUE THREAD

**Issue by kdenhartog** [decentralized-identity/sidetree#696]
Do we have any examples floating around of a full did document? I looked through the sidetree spec and sidtree API spec and didn't see any provided. In theory, the examples can come from did-core and be modified at this point, but was curious if anyone has already put one in the specs and I just missed them? If there isn't one, should we add it?

**Comment by OR13** [comment]
I would recommend taking a did:key and updating it:

```
{
  "@context": [
    "https://w3id.org/did/v0.11"
  ],
  "id": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs",
  "publicKey": [
    {
      "id": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs",
      "type": "Ed25519VerificationKey2018",
      "controller": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs",
      "publicKeyBase58": "AjRVKEUmMhPKFd44UKTYToDQ1QCXqnYTnQ91roNgjh9V"
    }
  ],
  "authentication": [
    "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs"
  ],
  "assertionMethod": [
    "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs"
  ],
  "capabilityDelegation": [
    "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs"
  ],
  "capabilityInvocation": [
    "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs"
  ],
  "keyAgreement": [
    {
      "id": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#zCBRPtzhiPyyMAS4xfC7C9eahSjoLXNfUJaGL7NaYBrCAb",
      "type": "X25519KeyAgreementKey2019",
      "controller": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs",
      "publicKeyBase58": "BvgBdWuCcE4jL1zCncdBVR29VXXZoxrogP35XVjnjx4P"
    }
  ]
}
```

^ this is all that is needed to handle VC / EDV / Encryption... its generally the first did method I use when testing a system.

**Comment by OR13** [comment]
add an `@base` and shorten it up a bit.

**Comment by kdenhartog** [comment]
Do we return publicKeys like this?

```json
{
      "id": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs#zCBRPtzhiPyyMAS4xfC7C9eahSjoLXNfUJaGL7NaYBrCAb",
      "type": "X25519KeyAgreementKey2019",
      "controller": "did:key:z6MkpBgXuUjChEsnN7tm9tRPJtmPpyUPFfnpUR3wh5Lheuvs",
      "publicKeyBase58": "BvgBdWuCcE4jL1zCncdBVR29VXXZoxrogP35XVjnjx4P"
}
```

I was thinking @troyronda said they take in JWKs only, but can produce these key types on request by doing transforms in the resolver.

**Comment by troyronda** [comment]
@kdenhartog 

> I was thinking @troyronda said they take in JWKs only, but can produce these key types on request by doing transforms in the resolver.

Correct.

**Comment by kdenhartog** [comment]
I don't need any action taken by this issue anymore so closing it. If anyone comes across this and needs an example of one check out the [ion explorer](https://identity.foundation/ion/explorer/?did=did%3Aion%3AEiAnKD8-jfdd0MDcZUjAbRgaThBrMxPTFOxcnfJhI7Ukaw%3AeyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJzaWdfNzJiZDE2ZDYiLCJwdWJsaWNLZXlKd2siOnsiY3J2Ijoic2VjcDI1NmsxIiwia3R5IjoiRUMiLCJ4IjoiS2JfMnVOR3Nyd1VOdkh2YUNOckRGdW14VXlQTWZZd3kxNEpZZmphQUhmayIsInkiOiJhSFNDZDVEOFh0RUxvSXBpN1A5eDV1cXBpeEVxNmJDenQ0QldvUVk1UUFRIn0sInB1cnBvc2VzIjpbImF1dGhlbnRpY2F0aW9uIiwiYXNzZXJ0aW9uTWV0aG9kIl0sInR5cGUiOiJFY2RzYVNlY3AyNTZrMVZlcmlmaWNhdGlvbktleTIwMTkifV0sInNlcnZpY2VzIjpbeyJpZCI6ImxpbmtlZGRvbWFpbnMiLCJzZXJ2aWNlRW5kcG9pbnQiOnsib3JpZ2lucyI6WyJodHRwczovL3d3dy52Y3NhdG9zaGkuY29tLyJdfSwidHlwZSI6IkxpbmtlZERvbWFpbnMifV19fV0sInVwZGF0ZUNvbW1pdG1lbnQiOiJFaUR4SWxJak9xQk5NTGZjdzZndWpHNEdFVDM3UjBIRWM2Z20xclNZTjlMOF9RIn0sInN1ZmZpeERhdGEiOnsiZGVsdGFIYXNoIjoiRWlBLXV3TWo3RVFheURmWTRJS3pfSE9LdmJZQ05td19Tb1lhUmhOcWhFSWhudyIsInJlY292ZXJ5Q29tbWl0bWVudCI6IkVpQ0czQ1M5RFJpeU1JRVoxRl9sSjZnRVRMZWVHREwzZnpuQUViMVRGdFZXNEEifX0%23sig_72bd16d6)
