### ISSUE TITLE
Loop through all create/recover operations until a complete delta state is applied

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#704]
Currently operation application logic treats the document state as "empty" (ie. { }) if a create/recover operation's fails to be applied and moves on to the next operation in operation chain.

However this would mean that in the scenario of: there exists no subsequent operation in operation chain, but there is a corrective create/recover operation, the corrective operation would be ignored, potentially leading to an unrecoverable DID.

**Comment by isaacJChen** [comment]
After discussion, decided that this change is unnecessary.
