### ISSUE TITLE
Rename transactionTime to ledgerTime, etc.

### ISSUE THREAD

**Issue by julio-cabdu** [decentralized-identity/sidetree#707]
Hi! Although the spec defines [ledger time](https://identity.foundation/sidetree/spec/#ledger-time), I've noticed that in the [implementation document](https://github.com/decentralized-identity/sidetree/blob/master/docs/implementation.md) and [other files](https://github.com/decentralized-identity/sidetree/pull/691#discussion_r430780206), other terms are used instead, such as transactionTime, blockchainTime, etc. Calling them "transaction" is not as accurate since transactions are timestamped in blocks - shall we rename to ledgerTime, ledgerTimeHash, etc?

**Comment by OR13** [comment]
i've also been bothered by this... but naming is hard.

The spec is the source of truth, there will be multiple implementation guides / reference implementations in other languages, etc...

ledgerTime <= blockNumber
ledgerTimeHash <= transactionNumber

Is this the proposal?

**Comment by julioCabDu** [comment]
Right, that's a good point regarding multiple future implementations, but since this is the first one, it could be cool to have some naming conventions from the beginning.
ledgerTime <= transactionTime
ledgerTimeHash <= transactionTimeHash
and anywhere else referring to time variables.

**Comment by csuwildcat** [comment]
Some of this was adopted and been included in v1.0 of the spec. Closing as completed, but feel free to reopen if future changes are desired.
