### ISSUE TITLE
Commitment Value Generation Paragraph

### ISSUE THREAD

**Issue by tplooker** [decentralized-identity/sidetree#716]
- Add definition link for commitment value
- Restructure first sentence to make the relationship to JWK and JCS clearer

**Comment by tplooker** [comment]
Define the reveal value as the raw value that is inputed into producing a commitment. Where the outputted value of the commitment process is the committed value.

**Comment by tplooker** [comment]
Changes captured in #729

**Comment by troyronda** [comment]
Closing as #729 was merged.
