### ISSUE TITLE
Define nonce and its use with commit/reveal for operations

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#737]
@csuwildcat to add detail about this to the issue.

**Comment by OR13** [comment]
@csuwildcat to add detail here.... something like:

"we propose injecting a nonce into the JWK before applying JCS, so that the same key can be safely reused for commitments".

**Comment by tplooker** [comment]
+1 to having a firm definition about this in the spec, if different implementations generating ion did's decide to do this differently then interoperability around recovery across wallets would be problematic.

**Comment by troyronda** [comment]
@OR13 @csuwildcat @tplooker Is there followup for this issue?

**Comment by OR13** [comment]
Imagine needing to generate a new key for every did document update operation.... thats what the spec basically says today.

**Comment by troyronda** [comment]
Action: Update spec to allow implementors to have a `nonce` value in the JWK.
@csuwildcat
