### ISSUE TITLE
Do we support customzied attributes in did document? 

### ISSUE THREAD

**Issue by bjwswang** [decentralized-identity/sidetree#740]
As far as I know , we have pub keys and service endpoints in did document, but what if I want to add some other attributes in did document. Can I do this  ?
If the answer is yes, how to do that?
If the answer is no, do we have any plan or considertation on this ? 
Thanks in advance! ^^

**Comment by bjwswang** [comment]
@csuwildcat  totally agreed with you. Casual properties in did document could lead to disasters.
actually we are using this sidetree protocol to do experiments with our business. Here we want to have some business specific variables to be included in document  especially a property to indicate what kind of role the current did owner is.  @OR13 any idea on this?

**Comment by bjwswang** [comment]
@OR13   can you show me an exmaple on how to add custom properties in `did:elem` ?  btw.. `element` really is awesome!

**Comment by OR13** [comment]
@bjwswang if you are experimenting, I highly recommend you use `did:web`... however, you may add custom properties to element did documents using:

https://element-did.com/server/did/profile

after creating your wallet / did (we will cover the test net anchoring cost for you).

You can "edit did document"... be careful, with great power comes great responsibility... you can brick your DID.... we will calculate a JSON patch from the edited json, and add the `ietf-json-patch` to an update operation....

You will want to make sure that the property is defined in a JSON-LD context, or resolvers that care about JSON-LD semantics might drop the property... here is an example of how to define custom properties and have them show up even after JSON-LD processing:

https://github.com/decentralized-identity/sidetree/blob/master/contexts/sidetree-v0.0.0.jsonld#L18

**Comment by OR13** [comment]
@bjwswang  do you have any further questions or may I close this issue?

**Comment by bjwswang** [comment]
@OR13 no for now .thank you .I wil close now.
