### ISSUE TITLE
Operation key references

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#767]
The operation key type was removed from add-public-key, but there are remaining references in the spec. Examples:

- https://identity.foundation/sidetree/spec/#verifying
- https://identity.foundation/sidetree/spec/#did-operations (Sidetree Methods MAY choose to expose protocol operation keys in the DID Document.)

We should resolve the meaning of operation keys in the remaining sections.

**Comment by OR13** [comment]
This was implemented and merged.
