### ISSUE TITLE
Align Sidetree DID Parameters with DID Core Spec

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#769]
https://github.com/w3c/did-core/issues/36

When this gets closed, we should address it.

**Comment by csuwildcat** [comment]
Seems like we would just register `initial-state` as a generic official parameter, given what I read there - right?

**Comment by OR13** [comment]
correct.... sometimes it takes months to end up right back where you started :)

**Comment by csuwildcat** [comment]
![4945415c-e75f-4724-ae39-c5c4813dbedc](https://user-images.githubusercontent.com/131786/85597011-16153d00-b5ff-11ea-85cf-f44ac018607f.jpg)

**Comment by csuwildcat** [comment]
With the move to a fully qualified DID URI for long-form, this is no longer applicable.
