### ISSUE TITLE
Document that `delta` size check is against the encoded string

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#772]
No spec on this, but `delta` size check should be against the decoded buffer, but currently size check is against the encoded buffer.

**Comment by csuwildcat** [comment]
"The canonicalized buffer of each Chunk File delta entry MUST NOT exceed the MAX_DELTA_SIZE" - this is what is in the spec, and what I believe we have implemented, @thehenrytsai. If this is true on both accounts, I can close this out as done.
