### ISSUE TITLE
Remove replace patch type

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#800]
https://github.com/trustbloc/sidetree-core-go/issues/339

As we consider https://github.com/decentralized-identity/sidetree/issues/766 and https://github.com/decentralized-identity/sidetree/issues/781

we should consider getting rid of replace.... it exposes the "internal data model".

**Comment by troyronda** [comment]
And, for reference, here is the prior discussion: https://github.com/decentralized-identity/sidetree/issues/622

**Comment by OR13** [comment]
If we are considering destroying the create payloads / initial state.... we MUST fix this at the same time IMO... no reason to preserve something like this while creating a breaking change to create operations.

**Comment by csuwildcat** [comment]
This was decided months ago, after deliberation, PR review, and discussions, and a change now would break downstream deployments - it is unacceptable that we are relitigating yet another decision that has been made and executed.

**Comment by csuwildcat** [comment]
I also want to clarify that replace, despite using the word `document` does not expose anything different - it is literally just an array where you can pass the two other patch types together, instead of separately: https://identity.foundation/sidetree/spec/#replace. Please be accurate in your statements, especially given you are making a pronouncement as your justification to do something that will affect many manhours of development.

**Comment by csuwildcat** [comment]
I will further note that this patch type is OPTIONAL, thus you don't even have to support it. This issue is coming from two other orgs who don't want to support it, don't have to, and yet are forcing other folks to adopt that view.

**Comment by OR13** [comment]
we are trying to clean up the sidetree spec, but it sounds like ION will have `replace` forever, and that because long form dids rely on replace.... all Microsoft DIDs will have this forever.... and because of that, we cannot update the spec or reference implementation to remove it... as you said, it's optional.

Just to be clear, despite the fact that we have not released a version of the sidetree spec, we are in capable of removing the replace operation because Microsoft has implemented support for it?

**Comment by csuwildcat** [comment]
We now are relying on this patch action in deployed apps/services, and did so after squaring it with the WG at the time this was discussed/accepted previously. It would be difficult for us to change this now, regardless of how much I may personally agree/disagree with doing so.

**Comment by csuwildcat** [comment]
Closing as we decided this would remain, due to dependencies on it.
