### ISSUE TITLE
Should sidetree rely on a styleguide for JSON?

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#805]
https://github.com/json-api/json-api/issues/1255
https://www.w3schools.com/js/js_conventions.asp
https://google.github.io/styleguide/jsoncstyleguide.xml
https://jsonapi.org/recommendations/#naming

**Comment by OR13** [comment]
I suggest we should just do whatever json-api says to do.... going our own way here is likely to result in endless issues... I would much rather just say.... see our style guide, we didn't invent it.

**Comment by OR13** [comment]
This was discussed previously here: https://github.com/decentralized-identity/sidetree/issues/749

**Comment by OR13** [comment]
I think the action here is to make sure we document why our JSON structures do or do not conform to a style guide.

**Comment by csuwildcat** [comment]
We already had consensus agreement on casing with PRs reviewed and accepted long ago. It is a bad practice, and harmful to all those who actually are impacted by the code churn, to not let our decisions as a group be final, within reason, serious bugs/issues withstanding. I would oppose a change now, because there are valid arguments to be made againstUsingCamelCase vs using_snake_case, and because this represents a burden on those doing the actual work, with literally 0 technically effective advantage.

**Comment by OR13** [comment]
Lets get our decision to handle JSON differently than google and json-api documented in the spec and we can close this issue :) 

The more I think about this, the more I think we made a mistake... read the original issue: https://github.com/decentralized-identity/sidetree/issues/749

We basically decided to close it, because we didn't want to break compatibility... but with things like SIP-1 / removing `replace` a possibility, I think its fair to reopen this issue, and seek a better solution.

**Comment by tplooker** [comment]
+1 to having consistency, as @wyc put it beautifully in slack this morning

> i will accept a consistent abomination over abominable inconsistency

The context of the statement was around debating which is better snake_case kebab-case or camelCase, for which people have endless opinions on.

At present in this spec we use kebab-case and snake_case, I really dont care what we use but it should be just the one.

**Comment by csuwildcat** [comment]
I want to be very clear: all properties in the spec are snake case. The one thing that isn't is a string value (not property) in the patch data. I didn't realize we were imposing anything on values, and really hope we don't adjudicate this with real risks in plat related to code/operation churn. I would ask that any nit-level changes from here on out be accompanied by PRs that change literally everything affected in the reference implementation. I believe requiring more skin in the game for changes that cause real code, operational, and deployment impacts will probably help focus our efforts on the things that are the most important.

**Comment by julio-cabdu** [comment]
The spec itself is cohesive around snake_case but the reference implementation not always, e.g. for delta, the Delta Model has the property updateCommitment - and that goes inside the JSON Chunk files - so not 100% consistent, which makes it messy for projects using this repo as a dependency.

**Comment by julio-cabdu** [comment]
Another example is the SignedDataModel in the DeactivateOperation that has its properties in camelCase. 
The input operation buffer must have properties in snake_case, but the return properties of signedData are camel. Therefore, when constructing the signed data input with a model in snake, then that same model cannot be used to ratify the type of output.deactivateOperation.signedData since the return values are in camel. It is also happening with other models so a solution could be changing all models to snake_case.

**Comment by OR13** [comment]
@csuwildcat we encourage feedback, we don't need to agree with the comments to be glad that people are participating. 

Following a documented style guide for the JSON protocol objects is not an unreasonable request. 
We need to document why we are doing something different than:

https://github.com/json-api/json-api/issues/1255

- JSON.org:
- Google JSON Style Guide (they follow the JSON.org spec):
- Schema.org
- W3resource
- Mozilla Objects and properties
- [W3School's JS JSON and JS Conventions
- Codecademy
- graphql spec uses camelCase for fields.

See also https://stackoverflow.com/questions/5543490/json-naming-convention

From the Microsoft API style guide:
https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#710-response-formats

`JSON property names SHOULD be camelCased.`

If the reason we have chosen to not follow a common style guide, can be put into writing, I think it will help people understand.

**Comment by csuwildcat** [comment]
Yet somehow most entities in the market (see below) don't reflect that opinion. I guess we should insist that all these stupid companies who have gone a different direction should all immediately move to correct their terrible decisions, regardless of the impact on the pressing things they must address that are core to their efforts?

- Github: https://developer.github.com/v3/repos/#response
- Twitter: https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object
- Slack: https://api.slack.com/messaging/retrieving#pulling_threads (edited) 
- Instagram: https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields
- Reddit: https://www.reddit.com/dev/api#GET_subreddits_{where} (edited)

**Comment by OR13** [comment]
Most entities in that list, are smaller than Microsoft and Google... but feel free to share a style guide that we can cite as the one we are using which uses snake case.

**Comment by OR13** [comment]
https://github.com/decentralized-identity/sidetree/blob/eaca9d74786c663e4d8a1c0c176714dad9528215/tests/core/DocumentComposer.spec.ts#L350

FYI, this casing change caused us some headaches as we are trying to generate test vectors...

`publicKeys` is now `public_keys`... and it eventually becomes `publicKey`...

**Comment by OR13** [comment]
@thehenrytsai assigning you to find a styleguide that supports the casing, and any other decisions we have made that deviate from google and ms standard approaches.

**Comment by troyronda** [comment]
We have a style guide now.
