### ISSUE TITLE
Deactivate operation potentially not working.

### ISSUE THREAD

**Issue by gjgd** [decentralized-identity/sidetree#820]
Looking at this code, it looks like only create update and recover operations are being processed in the TransactionProcessor:
https://github.com/decentralized-identity/sidetree/blob/master/lib/core/versions/latest/TransactionProcessor.ts#L206-L266

It seems that a deactivate operation would just be ignored here. I'm trying to find an integration test that checks that deactivate operations are working but I don't see any. We need to have integrations tests that verify all operations are working. 

Tests such as the one below are not enough because they don't use the TransactionProcessor: https://github.com/decentralized-identity/sidetree/blob/05af0c56d993632311f640290a286e2e5b9df12d/tests/core/Resolver.spec.ts#L120

**Comment by gjgd** [comment]
I can confirm that there are no integration tests for the deactivate operation by adding this check [here](https://github.com/decentralized-identity/sidetree/blob/master/lib/core/versions/latest/TransactionProcessor.ts#L224)

```js
    if (deactivateOperations.length > 0) {
      throw new Error('This code path was hit');
    }
```

No error is thrown when running `npm test`, so this code path was never hit.

With the same method, I was able to verify that the recover operation is not tested either.

**Comment by thehenrytsai** [comment]
Fixed, added a test to prevent regression.
