### ISSUE TITLE
spec: clarify steps in case of patch error for update operation

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#834]
According to spec (Step 6. in https://identity.foundation/sidetree/spec/#update-operation-processing) if an error is encountered during update operation patch processing we should exit update operation and advance to compiled state processing. 

In this case there is no ability to issue another valid update operation to correct the situation. 

I think it should not advance to compiled state processing but continue to the next update operation. Reference app is applying first valid update operation for that commitment value. I think that reference app behaviour is correct.

https://github.com/trustbloc/sidetree-core-go/issues/385

**Comment by sandrask** [comment]
There is still discrepancy between reference app and spec. Comment related to functionality: https://github.com/decentralized-identity/sidetree/issues/836#issuecomment-675600865

**Comment by troyronda** [comment]
Presumably related to #858

**Comment by troyronda** [comment]
Resolution: spec should be updated.

**Comment by thehenrytsai** [comment]
WG decided that recovery and update ops will diverge in behavior in case of missing delta:
in update -> we pretend the operation doesn't exist, keep looking for another op with the expected reveal value
in recover -> we treat the operation as success, return empty DID document and increment next update commitment

**Comment by csuwildcat** [comment]
The documentation for this was added in the last PR.
