### ISSUE TITLE
spec: clarify steps in case of patch error for recover operation

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#835]
There is discrepancy between spec and reference application.

According to spec (Step 7. in https://identity.foundation/sidetree/spec/#recovery-deactivate-operation-processing) if an error is encountered during recover operation patch processing we should use the new Next Recovery Commitment in another run of the recovery and deactivate operation processing loop

If applying patches fails reference application is not updating next recovery commitment in did state. It continues using next recovery commitment from the last successful operation (previous did state).

https://github.com/decentralized-identity/sidetree/blob/0042dcd95016982ce128e4c52618fd06bf647bf8/lib/core/versions/latest/OperationProcessor.ts#L217

**Comment by sandrask** [comment]
@thehenrytsai @csuwildcat @troyronda Currently reference application is not updating next recovery commitment in did state if applying patches fails for recover operation. Will reference application be updated to match the spec?

**Comment by troyronda** [comment]
https://github.com/decentralized-identity/sidetree/issues/744

**Comment by sandrask** [comment]
This has been fixed in reference application to match the spec #744. Basically, in case of create and recover operations Sidetree application should advance commitments as soon as they become available during operation processing. I am OK with this approach.
