### ISSUE TITLE
spec: clarify meaning of "next entry" in case of Create patch error

### ISSUE THREAD

**Issue by troyronda** [decentralized-identity/sidetree#837]
> Create: Apply the patch as directed by the Patch Action type specified by the action property. If any part of the patch fails or produces an error, reverse all modifications to the DID’s state and proceed to the next entry.

It would be good to be more precise about the meaning of "next entry".

**Comment by sandrask** [comment]
@troyronda I would modify the spec as follows: "If any part of the patch fails or produces an error, reverse all modifications to the DID’s state and proceed to the next available operation in the create operation pool".
