### ISSUE TITLE
Spec: kid MUST be present in the protected header

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#841]
Step 1. in https://identity.foundation/sidetree/spec/#signing states:

1. kid MUST be present in the protected header.

Reference application doesn't use kid and it expects only one header 'alg'. https://github.com/decentralized-identity/sidetree/blob/0dbf2c8ce6ef8981ebc6735066841bce39e2648f/lib/core/versions/latest/util/Jws.ts#L43

Also, fixtures don't have kid in the protected header.

**Comment by OR13** [comment]
See also: https://github.com/decentralized-identity/did-jose-extensions/blob/master/options.md

**Comment by OR13** [comment]
Recommend we change this to a MAY....

**Comment by sandrask** [comment]
I am ok with MAY

**Comment by sandrask** [comment]
This has been fixed.
