### ISSUE TITLE
Deprecate support for `initial-state`

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#849]
The `initial-state` parameter is officially not going to be a first-class parameter, and the https://w3c.github.io/did-core/#did-subject language on DID now allows the multiple representation of the same DID and concept of a 'canonical' DID.

Thus we should deprecate `initial-state`.

**Comment by isaacJChen** [comment]
https://github.com/decentralized-identity/sidetree/pull/963

done
