### ISSUE TITLE
Update JSON-LD Context for DID Resolution response... 

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#850]
https://www.w3.org/ns/did-resolution/v1  -> good luck getting this to go anywhere....

https://w3id.org/did-resolution/v1 -> will work when this is merged: https://github.com/w3c-ccg/did-resolution/pull/56

**Comment by OR13** [comment]
Not that did resolution responses are currently malformed JSON-LD due to this.

**Comment by OR13** [comment]
This change would image test vectors, so it should be considered breaking.

**Comment by OR13** [comment]
Consider also that the properties sidetree is returning do not match the did resolution spec.... thanks for pointing this out @gjgd .

**Comment by troyronda** [comment]
Looks like API spec was updated: https://identity.foundation/sidetree/api/#sidetree-resolution

Is this issue resolved @OR13 ?

**Comment by OR13** [comment]
I believe this issue has been resolved, by the team and microsoft!
