### ISSUE TITLE
Does this project comply with W3C specifications?

### ISSUE THREAD

**Issue by 99Kies** [decentralized-identity/sidetree#859]
Does this project comply with W3C specifications?

<https://www.w3.org/TR/did-use-cases/>

Can you provide me with a detailed document of the deployment API?
I tried to use the `docker-compose` startup service and unfortunately it failed

**Comment by csuwildcat** [comment]
@99Kies Yes, this is a protocol that implements the W3C Decentralized Identifier specification for representation of DID PKI metadata.

Which docker compose did you try?

**Comment by 99Kies** [comment]
> @99Kies Yes, this is a protocol that implements the W3C Decentralized Identifier specification for representation of DID PKI metadata.
> 
> Which docker compose did you try?

https://github.com/decentralized-identity/sidetree/blob/master/docs/docker.md

**Comment by csuwildcat** [comment]
Ah, thank you for pointing this out - that's an old docker build. The reference itself requires a blockchain/ledger and some other things, of which ION is the main implementation currently. There is a thread on a better docker setup here: https://github.com/decentralized-identity/ion/pull/105

We need to update this now, with the move to a full go-ipfs node, as that has docker configuration/setup impact.

**Comment by csuwildcat** [comment]
We will be updating the build for 1.0, please reopen if that build has issues.
