### ISSUE TITLE
I object to the publication of this specification as a stable version

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#867]
Per the contributing guidelines defined:

https://github.com/decentralized-identity/sidetree/blob/master/CONTRIBUTOR.md

I object to the use of spec-up as the specification tool used to produce this specification.

spec up is not maintained by DIF and has 1 contributor.

spec up has not been approved for the delivery of specifications that meet the guidelines of a standards organization.

DIF has not approved spec up for delivery of stable specifications.

DIF has no formal requirements for specifications documented anywhere. The DIF charter notes this is up to the working group to decide.

For those looking for "versions" of this spec, please use the internet archive, as there is no formal versioning / release process defined for this specification today:

https://web.archive.org/web/20200721150053/https://identity.foundation/sidetree/spec/v0.1.0/

**Comment by OR13** [comment]
Related reply: https://github.com/decentralized-identity/presentation-exchange/issues/115#issuecomment-698944236

**Comment by troyronda** [comment]
With "spec up" moved into DIF, I assume this issue resolved @OR13 ?

**Comment by OR13** [comment]
I still hate it, but since I am no longer forced to use it (since I am no longer an editor), I won't object to a stable version being published with it.... I think there remain questions about the sidetree spec and its formality / requirements to be published as a DIF standard vs, W3C or IETF.
