### ISSUE TITLE
Investigate and decide if delta validation should happen at observing time

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#880]
Right now, delta validation happens at resolution time for performance concerns. If done during observing time, validation may take too long, it can potentially bleed into the next time transaction time and build up a queue.

With SIP2, it may be possible to perform delta validation at observing time. We need to analyze the performance for it and decide if it is worth it to move validation to observing time in order to save space.

**Comment by csuwildcat** [comment]
@isaacJChen did we decide on this? If so, can we close the Issue?
