### ISSUE TITLE
consider restructuring fixtures to be JSON files

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#883]
for clients that are running in the browser, or another language, its easier to consume JSON than it is to rely on `fs` and `path` or their equivalents in other languages.... this also helps you group your fixtures, and can result in less of them for implementers to manage.

See https://github.com/transmute-industries/sidetree.js/tree/master/packages/test-vectors

^ this package just converts json files into an npm module... it runs in the browser, because it doesn't use `fs` or `path`.

**Comment by thehenrytsai** [comment]
@OR13, I think looks like this is done. Please feel free to reopen if you do not believe this is the case.
