### ISSUE TITLE
Discuss `verificationMethod` enum value in public key `purpose`

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#894]
Today, `purposes` array is intended to represents `verification relationships` in DID Core spec. However, `verification method` is not one of the spec-ed verification relationships and yet we have it as one of the allowed values in the enum. We need to discuss explicitly the handling of "verification method".

**Comment by troyronda** [comment]
This topic will be discussed during the 10/27/2020 WG meeting.

**Comment by thehenrytsai** [comment]
Duplicate to #905, will close this one.
