### ISSUE TITLE
Align remove-public-keys and remove-services on use of `ids` property

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/sidetree#897]
Currently `remove-public-keys` uses a `publicKeys` field for its array of key ID strings to be removed, whereas `remove-services` uses `ids` for the same array of ID strings. We should change `remove-public-keys` to use the same `ids` property to normalize this.

NOTE: this has already been changed in the spec to reflect the use of `ids` as the property name in both places.

**Comment by troyronda** [comment]
Normalizing with `ids` makes sense to me.

**Comment by thehenrytsai** [comment]
Done.
