### ISSUE TITLE
Test vectors: Long form resolution result has different format

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#899]
Test vectors: Long form resolution result is different from short form resolution result.
https://github.com/decentralized-identity/sidetree/blob/master/tests/vectors/resolution/longFormResponse.json
https://github.com/decentralized-identity/sidetree/blob/master/tests/vectors/resolution/shortFormResponse.json

This issue has been fixed with SIP-2 however it showed up again with commit for #895

**Comment by OR13** [comment]
yep, IMO the vectors themselves should map to the external resolution response, and we should avoid leaking "internal data structure", such as "status" in test vectors.

**Comment by OR13** [comment]
test vectors should be:

json input, json output.... with as close to standards, spec structures as possible, and as little implementation specific stuff as possible.

**Comment by thehenrytsai** [comment]
Just took a look, both files originated from Orie PR for the style conformance. But after a quick search, I don't even know where `shortFormResponse.json` is even used, perhaps it should just be removed.

**Comment by OR13** [comment]
PR to remove it: https://github.com/decentralized-identity/sidetree/pull/901

**Comment by sandrask** [comment]
Is it possible to change long form format response not to have body and status? It should only have resolution result just like afterCreate.json

**Comment by thehenrytsai** [comment]
@sandrask, PR created for your above request.

**Comment by thehenrytsai** [comment]
Fixed.

**Comment by sandrask** [comment]
> @sandrask, PR created for your above request.

thank you
