### ISSUE TITLE
Sidetree Spec should use hex code for defining multiformats associated with multihashes

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#915]
https://github.com/multiformats/js-multiformats#multihash-hashers
https://github.com/multiformats/multicodec/blob/master/table.csv#L9

For example: "sha2-256" ==== "0x12"... we should use "0x12" in the spec.

**Comment by OR13** [comment]
IMO this is only a spec issue, internal solutions to this are not relevant. (this is not a reference implementation issue)

**Comment by troyronda** [comment]
Spec should be updated to refer to the table.

**Comment by csuwildcat** [comment]
Action: ask @thehenrytsai about the status of this in the implementation.

**Comment by csuwildcat** [comment]
Action: Daniel to update spec

**Comment by troyronda** [comment]
- Terminology section
- Hashing function section
