### ISSUE TITLE
Permanent Long Form DIDs

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/sidetree#922]
Wondering if its worth allowing for a subset of long form DIDs to be permanent (never check the ledger) DIDs.

Use case being cases where we know they will NEVER use a ledger, and they still want to generate a DID Document.

If they create payload contained a value like "permanent / updated-able / bikeshed here"...

The identifier would be a function of this value, and did resolvers could be implemented as cleanly as they are for did:key, making 0 network requests and being a pure function of the didUniqueSuffix.

even better would be to prefix the did Unique Suffix in such a way that they could be distinguished without base64url decoding.

Since the question will be asked.

For these DIDs, their `canonicalId` would be the Long Form.

And their "Short Form" would never be valid.

**Comment by csuwildcat** [comment]
I don't see a reason why you/we couldn't add this. Probably would need to be a special segment, so it's technically a differentiated DID string.

**Comment by OR13** [comment]
@csuwildcat yes, it would be nice to be able to tell "this thing is not recoverable / permanent" just by looking at the did.

**Comment by chunningham** [comment]
KERI uses it's Identifier derivation code (first few characters of the identifier) to do this, "basic" identifiers (which represent public keys) come in two flavours, transferrable (can be updated) and non-transferrable (ephemeral as in `did:key`). As I understand, Sidetree is (currently) always multihash, makes a convenient equivalent to basic non-transferrable difficult without pre/postfixing an extra "flag" to the did. could something like `did:ion:ephem:<multibase/codec pubkey>` work? feels unnecessary to include the network name for an ephemeral id

**Comment by csuwildcat** [comment]
Sidetree DIDs are not always multihash, and actually have multiple equivalent forms. The juggling act DIDs have to do for variants of IDs will get easier when we have the right equivalence expression capabilities in DID Core.

**Comment by csuwildcat** [comment]
This would need a specific proposal to add, and we should probably think about stuff like this as post-v1

**Comment by OR13** [comment]
The proposal is to register a sidetree did docuemnt type that is "off ledger only" that allows you to skip checking the ledger entirely.... and would make sidetree long form dids loosely equivalent to did:key.

I agree its a nice to have, and I would personally recommend did:key over sidetree for that use case.
