### ISSUE TITLE
Default Compression Algorithm should be "GZIP"

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#925]
Specification states that default compression algorithm value is ZIP, however reference application is using GZIP.

**Comment by sandrask** [comment]
https://github.com/decentralized-identity/sidetree/blob/ed1999209a45fd1cb8426a30c2b50724a1a2f937/lib/core/versions/latest/util/Compressor.ts#L22

**Comment by sandrask** [comment]
@thehenrytsai @csuwildcat I added this issue to the agenda for today - hopefully you get a chance to look at it.

**Comment by sandrask** [comment]
Last week we have agreed that default protocol parameter should say GZIP, can you please change spec? @csuwildcat

**Comment by sandrask** [comment]
@csuwildcat this is still outstanding

**Comment by csuwildcat** [comment]
@sandrask it depends if we want to be more specific than just saying it needs to be gzip compliant.

**Comment by troyronda** [comment]
GZIP is more descriptive than ZIP.
