### ISSUE TITLE
Remove `deltaHash` from create request payload and long-form DID

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#934]
`deltaHash` is technically not required in the request and long-form DID because it can be computed from the given `delta` property.

If we were to take this change, I imagine the create payload would get rid of the `suffixData` wrapper property:

```json
    {
      "type": "create",
      "recoveryCommitment": "EiBfOZdMtU6OBw8Pk879QtZ-2J-9FbbjSZyoaA_bqD4zhA",
      "delta": { ... }
    }
```

Long form DID would also encode the above content as the initial state, this change will also make the long form DID like 50 bytes shorter.

**Comment by csuwildcat** [comment]
@thehenrytsai  What's the status here? Did we decide not to do this?

**Comment by thehenrytsai** [comment]
Yes, WG decided we won't take on this, because it involves flattening `suffixData` then we need to rename operation `type` and DID `type` etc.

Also another (not so strong) reason for not doing would be that the batch writer and long form resolver would need another way to know for sure what hash algorithm to use, but that can be solve using the same approach for #965.
