### ISSUE TITLE
Spec: "add-public-keys" patch typo

### ISSUE THREAD

**Issue by sandrask** [decentralized-identity/sidetree#945]
Point 3.3 in https://identity.foundation/sidetree/spec/#add-public-keys states:

"The key represented by the JWK object MUST be projected into the assertionMethod array of the DID Document upon resolution."

assertionMethod should be replaced with verificationMethod

**Comment by csuwildcat** [comment]
I am fixing this in another PR I started today.

**Comment by sandrask** [comment]
This is has been fixed.
