### ISSUE TITLE
Make applyFirstValidOperation in Resolver return previous did state instead of undefined 

### ISSUE THREAD

**Issue by isaacJChen** [decentralized-identity/sidetree#981]
- Make sure no side effects if this change is taken.
- Make applyFirstValidOperation in Resolver return previous did state instead of undefined when no operation can be applied.

**Comment by thehenrytsai** [comment]
Closing this issue as won't fix.

Making the failure explicit is better than the current approach of inferring failure based on transaction number, it will also be more consistent with the pattern used downstream.

See also https://github.com/decentralized-identity/sidetree/issues/1171.
