### ISSUE TITLE
Remove the requirement on TransactionFeePaidLessThanNormalizedFee

### ISSUE THREAD

**Issue by thehenrytsai** [decentralized-identity/sidetree#983]
Revisit the requirement in code that requires the ION transaction fee paid to be at least the same as the normalize fee (search `TransactionFeePaidLessThanNormalizedFee`).

Also remove the counter part in `computeMinimumTransactionFee()` because there is no need for it since bitcoin service already does it better by comparing against the actual current estimated transaction fee.

**Comment by isaacJChen** [comment]
Decided no change after discussion. Normalized fee will be used to encourage batching and prevent miners from being able to write with no fee.
