### ISSUE TITLE
Parsing 4-segment DIDs is ambiguous

### ISSUE THREAD

**Issue by jmandel** [decentralized-identity/sidetree#996]
On my reading, https://identity.foundation/sidetree/spec/#method-versioning defines:

    did:<method>:<network>:<didUniqueSuffix>

... whereas https://identity.foundation/sidetree/spec/#long-form-did-uris defines:

    did:METHOD:<did-suffix>:<long-form-suffix-data>

... so it's unclear whether a 4-segment sidetree DID matches one of these patterns or the other.

In real life, I'm sure there are heuristics that work fine, but is this ambiguity intentional and necessary? It's something that could be addressed with prefixes, name/value pairs, or even collapsing method+network into a single segment.

**Comment by jmandel** [comment]
(Note also the inconsistent syntax and segment naming in the two citations above; would be good to ensure they're aligned.)

**Comment by csuwildcat** [comment]
Action: Daniel to propose PR that specifies handling

**Comment by troyronda** [comment]
Action: Informational recommendations. The method specifies the regex parsing rules.
@csuwildcat

**Comment by TomCJones** [comment]
I thought Markus made it clear that there is no such thinkg as a four segment did?
